#!/bin/bash
# Regenerates the --il parity manifest (the golden-fixture digest table the
# IlParityGolden_Test.cpp regression runner verifies against:
# cpp/tests/Decompiler/Disassembler/data/il_parity_manifest.tsv).
#
# The manifest locks the whole-module `--il` disassembly byte-parity the
# full-corpus differential sweep established (the PD10 re-sweep: 282 of 286
# corpus rows byte-identical to the C# ilspycmd 11.0 oracle; the remaining 4
# rows are the malformed/native samples both engines refuse identically at
# rc 70 -- those never reach a successful dump and are excluded here by the
# rc-0 row filter). Every row is the SHA-1 of the CLI's raw `--il` stdout
# (CRLF included -- the same bytes ShowIL's output buffer carries, so the
# in-process test and this script hash identical digests).
#
# Run this ONLY to record an INTENTIONAL output change (a deliberate render
# change with controller sign-off); commit the regenerated manifest together
# with the change. An unexpected diff means the parity broke -- investigate,
# do not regenerate.
#
# Usage: il_parity_manifest.sh [output-tsv]
#   ILSPY_PORT   the port's CLI (default: this repo's linux-ninja build)
#   CORPUS_DIR   the net48 corpus dir (default the fixture install)
#   CAPA_DIR      the capa sample dir (default /home/jim/source/capa-testfiles)
#   TIMEOUT       per-run timeout in seconds (default 120)

set -u

REPO=$(cd "$(dirname "$0")/../.." && pwd)
PORT=${ILSPY_PORT:-"$REPO/build/linux-ninja/ILSpyCmd/ilspy_cli"}
CORPUS_DIR=${CORPUS_DIR:-/home/jim/ilspy-test-fixtures/net48}
CAPA_DIR=${CAPA_DIR:-/home/jim/source/capa-testfiles}
OUT=${1:-"$REPO/tests/Decompiler/Disassembler/data/il_parity_manifest.tsv"}
TIMEOUT=${TIMEOUT:-120}

# One manifest row: <corpus> <path-relative-to-corpus-root> <sha1-of-stdout>.
# Only rc-0 rows are emitted (a sample the CLI refuses -- the malformed set --
# has no successful dump to pin; the row drops out).
emit_row() {  # $1=corpus  $2=relpath  $3=abs-sample-path
  local corpus="$1" rel="$2" sample="$3" rc sha
  timeout "$TIMEOUT" "$PORT" "$sample" --il > /tmp/il_parity_row.out 2>/dev/null
  rc=$?
  if [ "$rc" != "0" ]; then
    echo "  SKIPPED (rc=$rc, not pinned): $rel" >&2
    return
  fi
  sha=$(sha1sum /tmp/il_parity_row.out | cut -d' ' -f1)
  printf "%s\t%s\t%s\n" "$corpus" "$rel" "$sha" >> "$OUT"
}

mkdir -p "$(dirname "$OUT")"
{
  echo "# The --il whole-module parity manifest (see il_parity_manifest.sh"
  echo "# for the regeneration procedure and IlParityGolden_Test.cpp for the"
  echo "# verification contract)."
  echo "#"
  echo "# Columns: <corpus> <sample path relative to the corpus root> <sha1>"
  echo "# of the CLI's raw --il stdout (CRLF included). Corpus roots:"
  echo "#   net48 / facades -> ILSPY_TEST_NET48_DIR (facades rows live under"
  echo "#     Facades/ of the same root)"
  echo "#   capa            -> ILSPY_TEST_CAPA_DIR"
  echo "# Rows whose sample is absent on the running machine are SKIPPED by"
  echo "# the test, never failed. Generated by cpp/tests/tools/il_parity_manifest.sh."
} > "$OUT"

echo "net48 corpus: $CORPUS_DIR"
for f in "$CORPUS_DIR"/*.dll; do
  [ -f "$f" ] || continue
  emit_row net48 "$(basename "$f")" "$f"
done

echo "facades corpus: $CORPUS_DIR/Facades"
for f in "$CORPUS_DIR"/Facades/*.dll; do
  [ -f "$f" ] || continue
  emit_row facades "Facades/$(basename "$f")" "$f"
done

echo "capa corpus: $CAPA_DIR"
for f in "$CAPA_DIR"/*; do
  [ -f "$f" ] || continue
  grep -qa BSJB "$f" 2>/dev/null || continue
  emit_row capa "$(basename "$f")" "$f"
done

rm -f /tmp/il_parity_row.out
echo "manifest: $OUT ($(grep -vc '^#' "$OUT") rows)"
