// Copyright (c) 2026 ILSpy Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
// Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
// PARTICULAR PURPOSE, NONINFRINGEMENT, OR AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
// FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
// USE OR OTHER DEALINGS IN THE SOFTWARE.

// The --il whole-module parity lock: the golden-fixture digest manifest
// (data/il_parity_manifest.tsv, regenerated by
// cpp/tests/tools/il_parity_manifest.sh) pins the byte-parity the
// full-corpus differential sweep established -- every corpus sample the
// CLI decompiles with rc 0 renders the exact bytes the C# ilspycmd 11.0
// oracle rendered (282 of 286 rows; the 4 malformed/native samples both
// engines refuse identically at rc 70 never reach a successful dump and
// are excluded from the manifest by the rc-0 row filter).
//
// The verification is the in-process ShowIL entry (the same function the
// CLI's --il branch calls, its output buffer dumped verbatim to stdout --
// so the manifest's SHA-1 values, taken over the CLI's raw stdout with the
// CRLF line endings included, verify here unchanged). Any render change in
// the Disassembler family flips a digest and fails this test; a hard
// regression aborts the test process, which is the same red, less pretty.
//
// The corpus fixtures are machine-local (the net48 reference-assembly set
// and the capa-testfiles samples, the same corpora the differential sweep
// drove): rows whose sample file is absent on the running machine are
// SKIPPED and counted in the skip tally, never failed -- the lock only
// bites where the fixtures exist (ILSPY_TEST_NET48_DIR /
// ILSPY_TEST_CAPA_DIR select the roots; the defaults are this repo's
// staged locations).

#include "ILSpyCmd/IlspyCmdProgram.hpp"
#include "Decompiler/Util/Span.hpp"
#include "Decompiler/Util/Sha1ForNonSecretPurposes.hpp"

#include <gtest/gtest.h>

#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace {

namespace fs = std::filesystem;
namespace Cmd = ILSpy::ILSpyCmd;
using ILSpy::Decompiler::Util::Sha1ForNonSecretPurposes;

// The manifest, checked in under this test's data/ directory (the CMake
// source-dir definition the tests target carries).
fs::path ManifestPath() {
#ifdef ILSPY_TESTS_SOURCE_DIR
    return fs::path(ILSPY_TESTS_SOURCE_DIR) /
        "Decompiler/Disassembler/data/il_parity_manifest.tsv";
#else
    return fs::path("Decompiler/Disassembler/data/il_parity_manifest.tsv");
#endif
}

// The corpus roots (il_parity_manifest.sh's defaults mirrored; the env
// override is the ILSPY_TEST_MSCORLIB convention).
fs::path CorpusRoot(const std::string& corpus) {
    if (corpus == "capa") {
        if (const char* env = std::getenv("ILSPY_TEST_CAPA_DIR"))
            return fs::path(env);
#if !defined(_WIN32)
        return fs::path("/home/jim/source/capa-testfiles");
#else
        return fs::path();
#endif
    }
    // net48 and facades share one root (the facades rows carry the
    // Facades/ relative prefix in the manifest).
    if (const char* env = std::getenv("ILSPY_TEST_NET48_DIR"))
        return fs::path(env);
#if !defined(_WIN32)
    return fs::path("/home/jim/ilspy-test-fixtures/net48");
#else
    return fs::path();
#endif
}

struct ManifestRow {
    std::string corpus;
    std::string relPath;
    std::string sha1;
};

std::vector<ManifestRow> ReadManifest(const fs::path& path) {
    std::vector<ManifestRow> rows;
    std::ifstream in(path);
    if (!in) return rows;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::size_t a = line.find('\t');
        std::size_t b = line.find('\t', a + 1);
        if (a == std::string::npos || b == std::string::npos) continue;
        rows.push_back({line.substr(0, a), line.substr(a + 1, b - a - 1),
            line.substr(b + 1)});
    }
    return rows;
}

std::string Sha1Hex(const std::string& bytes) {
    std::uint8_t digest[20];
    Sha1ForNonSecretPurposes::HashData(
        ILSpy::Decompiler::Util::Span<const std::uint8_t>(
            reinterpret_cast<const std::uint8_t*>(bytes.data()), bytes.size()),
        ILSpy::Decompiler::Util::Span<std::uint8_t>(digest, sizeof(digest)));
    static const char* digits = "0123456789abcdef";
    std::string hex;
    hex.reserve(40);
    for (std::uint8_t b : digest) {
        hex.push_back(digits[b >> 4]);
        hex.push_back(digits[b & 0xF]);
    }
    return hex;
}

}  // namespace

// Every whole-module --il dump the manifest pins must render the exact
// recorded bytes: the digest lock over the full corpus (282 rows -- the
// net48 reference set, its facades, and the capa samples; absent fixtures
// skip, a digest mismatch fails with the offending rows listed).
TEST(IlParityGoldenTest, WholeModuleIlOutputsMatchTheManifest)
{
    const fs::path manifest = ManifestPath();
    const std::vector<ManifestRow> rows = ReadManifest(manifest);
    ASSERT_FALSE(rows.empty()) << "manifest unreadable: " << manifest.string();

    std::size_t verified = 0;
    std::size_t skipped = 0;
    std::vector<std::string> mismatches;
    for (const auto& row : rows) {
        const fs::path root = CorpusRoot(row.corpus);
        const fs::path sample = root / row.relPath;
        std::error_code ec;
        if (root.empty() || !fs::is_regular_file(sample, ec)) {
            ++skipped;
            continue;
        }
        std::ostringstream output;
        Cmd::InputPDBFile pdb;
        Cmd::ShowIL(sample.string(), output, /*showILSequencePoints=*/false, pdb);
        if (Sha1Hex(output.str()) != row.sha1) {
            mismatches.push_back(row.corpus + "\t" + row.relPath);
        } else {
            ++verified;
        }
    }
    // The per-row failure list (capped at 20 lines).
    std::string listed;
    for (std::size_t i = 0; i < mismatches.size() && i < 20; ++i)
        listed += "  " + mismatches[i] + "\n";
    if (mismatches.size() > 20)
        listed += "  ... and " + std::to_string(mismatches.size() - 20) +
            " more\n";
    EXPECT_TRUE(mismatches.empty())
        << mismatches.size() << " of " << rows.size()
        << " manifest rows render different bytes (corpus\tsample):\n"
        << listed;
    // The skip tally is visibility, not failure: a machine without the
    // corpus fixtures still runs the lock over whatever IS present. The
    // row accounting must close over verified + skipped + mismatched.
    if (verified + skipped + mismatches.size() != rows.size()) {
        ADD_FAILURE() << "row accounting broke: verified=" << verified
                      << " skipped=" << skipped << " mismatched="
                      << mismatches.size() << " rows=" << rows.size();
    }
}

// The refusal shape is NOT part of this lock: the 4 malformed/native
// samples (capa 0da87fccbf / 6f9cb3f56d / kernel32-64.dll_ / net064
// System.EnterpriseServices.Thunk) never reach a successful dump -- the
// CLI refuses them at the open (rc 70, empty stdout, both engines), a
// shape the PD7 ClassifyCliOpenFailure tests already pin.
