// Copyright (c) 2026 ILSpy Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files ("the Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// The BamlNode.Parse gold: the crafted Parse-shape .baml streams (the
// omitted-end, unexpected-footer, leaf-first, truncated, two-document,
// empty, and unmatched-footer shapes no real fixture exercises) and the
// block trees the REAL ICSharpCode.BamlDecompiler BamlNode.Parse produces
// over the identical bytes (BamlProbe, out/*.dump.txt). The tree render is
// the probe's DumpTree format: "B <headerType> @<pos> F=@<pos>:<type>" per
// block ("F=@null" while an end record stays omitted), "R <type> @<pos>"
// per record leaf, children indented two spaces.
//
// The truncated fixture's gold shows the C# innermost-return quirk: the
// dump walks from the node Parse RETURNS, and for a truncated document
// that is the innermost open block, not the root.

#pragma once

#include <cstring>
#include <string>

namespace ILSpy::Tests {

// t_omit.baml (44 bytes)
inline constexpr char kTOmitBamlHex[] =
    "0c0000004d005300420041004d004c0000006000000060000000600001000000"
    "0000000b0600030000000402";

inline std::string tOmitBamlBytes() {
    std::string bytes;
    bytes.reserve(std::strlen(kTOmitBamlHex) / 2);
    for (const char* p = kTOmitBamlHex; p[0] && p[1]; p += 2) {
        int hi = p[0] <= '9' ? p[0] - '0' : (p[0] | 32) - 'a' + 10;
        int lo = p[1] <= '9' ? p[1] - '0' : (p[1] | 32) - 'a' + 10;
        bytes.push_back(static_cast<char>(hi * 16 + lo));
    }
    return bytes;
}

// t_omit2.baml (47 bytes)
inline constexpr char kTOmit2BamlHex[] =
    "0c0000004d005300420041004d004c0000006000000060000000600001000000"
    "000000090800070500030000000402";

inline std::string tOmit2BamlBytes() {
    std::string bytes;
    bytes.reserve(std::strlen(kTOmit2BamlHex) / 2);
    for (const char* p = kTOmit2BamlHex; p[0] && p[1]; p += 2) {
        int hi = p[0] <= '9' ? p[0] - '0' : (p[0] | 32) - 'a' + 10;
        int lo = p[1] <= '9' ? p[1] - '0' : (p[1] | 32) - 'a' + 10;
        bytes.push_back(static_cast<char>(hi * 16 + lo));
    }
    return bytes;
}

// t_unexpected_footer.baml (29 bytes)
inline constexpr char kTUnexpectedFooterBamlHex[] =
    "0c0000004d005300420041004d004c0000006000000060000000600002";

inline std::string tUnexpectedFooterBamlBytes() {
    std::string bytes;
    bytes.reserve(std::strlen(kTUnexpectedFooterBamlHex) / 2);
    for (const char* p = kTUnexpectedFooterBamlHex; p[0] && p[1]; p += 2) {
        int hi = p[0] <= '9' ? p[0] - '0' : (p[0] | 32) - 'a' + 10;
        int lo = p[1] <= '9' ? p[1] - '0' : (p[1] | 32) - 'a' + 10;
        bytes.push_back(static_cast<char>(hi * 16 + lo));
    }
    return bytes;
}

// t_leaf_first.baml (33 bytes)
inline constexpr char kTLeafFirstBamlHex[] =
    "0c0000004d005300420041004d004c000000600000006000000060002d010000"
    "00";

inline std::string tLeafFirstBamlBytes() {
    std::string bytes;
    bytes.reserve(std::strlen(kTLeafFirstBamlHex) / 2);
    for (const char* p = kTLeafFirstBamlHex; p[0] && p[1]; p += 2) {
        int hi = p[0] <= '9' ? p[0] - '0' : (p[0] | 32) - 'a' + 10;
        int lo = p[1] <= '9' ? p[1] - '0' : (p[1] | 32) - 'a' + 10;
        bytes.push_back(static_cast<char>(hi * 16 + lo));
    }
    return bytes;
}

// t_truncated.baml (39 bytes)
inline constexpr char kTTruncatedBamlHex[] =
    "0c0000004d005300420041004d004c0000006000000060000000600001000000"
    "00000003000000";

inline std::string tTruncatedBamlBytes() {
    std::string bytes;
    bytes.reserve(std::strlen(kTTruncatedBamlHex) / 2);
    for (const char* p = kTTruncatedBamlHex; p[0] && p[1]; p += 2) {
        int hi = p[0] <= '9' ? p[0] - '0' : (p[0] | 32) - 'a' + 10;
        int lo = p[1] <= '9' ? p[1] - '0' : (p[1] | 32) - 'a' + 10;
        bytes.push_back(static_cast<char>(hi * 16 + lo));
    }
    return bytes;
}

// t_two_docs.baml (44 bytes)
inline constexpr char kTTwoDocsBamlHex[] =
    "0c0000004d005300420041004d004c0000006000000060000000600001000000"
    "000000020100000000000002";

inline std::string tTwoDocsBamlBytes() {
    std::string bytes;
    bytes.reserve(std::strlen(kTTwoDocsBamlHex) / 2);
    for (const char* p = kTTwoDocsBamlHex; p[0] && p[1]; p += 2) {
        int hi = p[0] <= '9' ? p[0] - '0' : (p[0] | 32) - 'a' + 10;
        int lo = p[1] <= '9' ? p[1] - '0' : (p[1] | 32) - 'a' + 10;
        bytes.push_back(static_cast<char>(hi * 16 + lo));
    }
    return bytes;
}

// t_empty.baml (28 bytes)
inline constexpr char kTEmptyBamlHex[] =
    "0c0000004d005300420041004d004c00000060000000600000006000";

inline std::string tEmptyBamlBytes() {
    std::string bytes;
    bytes.reserve(std::strlen(kTEmptyBamlHex) / 2);
    for (const char* p = kTEmptyBamlHex; p[0] && p[1]; p += 2) {
        int hi = p[0] <= '9' ? p[0] - '0' : (p[0] | 32) - 'a' + 10;
        int lo = p[1] <= '9' ? p[1] - '0' : (p[1] | 32) - 'a' + 10;
        bytes.push_back(static_cast<char>(hi * 16 + lo));
    }
    return bytes;
}

// t_unmatched_footer.baml (36 bytes)
inline constexpr char kTUnmatchedFooterBamlHex[] =
    "0c0000004d005300420041004d004c0000006000000060000000600001000000"
    "0000000c";

inline std::string tUnmatchedFooterBamlBytes() {
    std::string bytes;
    bytes.reserve(std::strlen(kTUnmatchedFooterBamlHex) / 2);
    for (const char* p = kTUnmatchedFooterBamlHex; p[0] && p[1]; p += 2) {
        int hi = p[0] <= '9' ? p[0] - '0' : (p[0] | 32) - 'a' + 10;
        int lo = p[1] <= '9' ? p[1] - '0' : (p[1] | 32) - 'a' + 10;
        bytes.push_back(static_cast<char>(hi * 16 + lo));
    }
    return bytes;
}

// The gold block tree over synth (41 dump lines).
inline constexpr const char* kSynthTreeGold[] = {
    "B DocumentStart @28 F=@351:DocumentEnd",
    "  R XmlnsProperty @35",
    "  R PIMapping @52",
    "  R AssemblyInfo @66",
    "  R StringInfo @102",
    "  R TypeInfo @112",
    "  R TypeSerializerInfo @124",
    "  R AttributeInfo @140",
    "  B ConstructorParametersStart @152 F=@156:ConstructorParametersEnd",
    "    R ConstructorParameterType @153",
    "  B ElementStart @157 F=@310:ElementEnd",
    "    B NamedElementStart @161 F=@167:ElementEnd",
    "    R ContentProperty @168",
    "    R Property @171",
    "    R PropertyWithConverter @177",
    "    R PropertyCustom @185",
    "    R PropertyWithExtension @195",
    "    R Text @202",
    "    R TextWithConverter @209",
    "    R TextWithId @216",
    "    R LiteralContent @220",
    "    R RoutedEvent @234",
    "    R PresentationOptionsAttribute @244",
    "    R LineNumberAndPosition @252",
    "    R LinePosition @261",
    "    B PropertyComplexStart @266 F=@303:PropertyComplexEnd",
    "      R PropertyStringReference @269",
    "      R PropertyTypeReference @274",
    "      B PropertyListStart @279 F=@290:PropertyListEnd",
    "        R StaticResourceId @282",
    "        R PropertyWithStaticResourceId @285",
    "      B PropertyArrayStart @291 F=@298:PropertyArrayEnd",
    "        R OptimizedStaticResource @294",
    "      B PropertyDictionaryStart @299 F=@302:PropertyDictionaryEnd",
    "    R DefAttribute @304",
    "  R DeferableContentStart @311",
    "  R DefAttributeKeyString @316",
    "  B StaticResourceStart @326 F=@330:StaticResourceEnd",
    "  B KeyElementStart @331 F=@341:KeyElementEnd",
    "  B ElementStart @342 F=@350:ElementEnd",
    "    R Text @346",
};
inline constexpr std::size_t kSynthTreeGoldCount = 41;

// The gold block tree over findtoolbar (809 dump lines).
inline constexpr const char* kFindToolbarTreeGold[] = {
    "B DocumentStart @28 F=@9457:DocumentEnd",
    "  R AssemblyInfo @35",
    "  R PIMapping @121",
    "  R PIMapping @189",
    "  R TypeInfo @257",
    "  B ElementStart @297 F=@9456:ElementEnd",
    "    R AssemblyInfo @301",
    "    R AssemblyInfo @384",
    "    R AssemblyInfo @472",
    "    R XmlnsProperty @565",
    "    R AssemblyInfo @634",
    "    R XmlnsProperty @717",
    "    R XmlnsProperty @776",
    "    R XmlnsProperty @830",
    "    R AttributeInfo @895",
    "    R PropertyWithConverter @911",
    "    R ConnectionId @923",
    "    R AttributeInfo @928",
    "    R PropertyWithConverter @940",
    "    R DefAttribute @958",
    "    R AttributeInfo @974",
    "    R PropertyCustom @990",
    "    R TypeInfo @997",
    "    R AttributeInfo @1043",
    "    R PropertyWithConverter @1072",
    "    R AttributeInfo @1087",
    "    R PropertyWithConverter @1108",
    "    R AttributeInfo @1123",
    "    R PropertyCustom @1143",
    "    R AttributeInfo @1150",
    "    B PropertyDictionaryStart @1167 F=@7153:PropertyDictionaryEnd",
    "      R StringInfo @1170",
    "      R AttributeInfo @1194",
    "      R StringInfo @1207",
    "      R AttributeInfo @1225",
    "      R AttributeInfo @1243",
    "      R AttributeInfo @1259",
    "      R AttributeInfo @1272",
    "      R StringInfo @1286",
    "      R StringInfo @1305",
    "      R StringInfo @1319",
    "      R StringInfo @1343",
    "      R AttributeInfo @1363",
    "      R AttributeInfo @1381",
    "      R AttributeInfo @1397",
    "      R AttributeInfo @1410",
    "      R AttributeInfo @1422",
    "      R AttributeInfo @1444",
    "      R AttributeInfo @1462",
    "      R AttributeInfo @1477",
    "      R AttributeInfo @1489",
    "      R AttributeInfo @1501",
    "      R AttributeInfo @1517",
    "      R AttributeInfo @1533",
    "      R AttributeInfo @1546",
    "      R AttributeInfo @1564",
    "      R AttributeInfo @1582",
    "      R AttributeInfo @1598",
    "      R AttributeInfo @1611",
    "      R StringInfo @1626",
    "      R AttributeInfo @1651",
    "      R AttributeInfo @1663",
    "      R AttributeInfo @1675",
    "      R AttributeInfo @1701",
    "      R AttributeInfo @1723",
    "      R AttributeInfo @1751",
    "      B ElementStart @1769 F=@7152:ElementEnd",
    "        R DeferableContentStart @1773",
    "        R DefAttributeKeyString @1778",
    "        R DefAttributeKeyString @1788",
    "        R DefAttributeKeyString @1798",
    "        R DefAttributeKeyString @1808",
    "        R DefAttributeKeyString @1818",
    "        R OptimizedStaticResource @1828",
    "        R DefAttributeKeyString @1832",
    "        R OptimizedStaticResource @1842",
    "        R DefAttributeKeyType @1846",
    "        R DefAttributeKeyType @1856",
    "        R OptimizedStaticResource @1866",
    "        R OptimizedStaticResource @1870",
    "        R OptimizedStaticResource @1874",
    "        R OptimizedStaticResource @1878",
    "        R OptimizedStaticResource @1882",
    "        R OptimizedStaticResource @1886",
    "        R OptimizedStaticResource @1890",
    "        R OptimizedStaticResource @1894",
    "        R DefAttributeKeyType @1898",
    "        R DefAttributeKeyType @1908",
    "        R DefAttributeKeyString @1918",
    "        R OptimizedStaticResource @1928",
    "        R OptimizedStaticResource @1932",
    "        R OptimizedStaticResource @1936",
    "        R OptimizedStaticResource @1940",
    "        R OptimizedStaticResource @1944",
    "        R OptimizedStaticResource @1948",
    "        R OptimizedStaticResource @1952",
    "        R OptimizedStaticResource @1956",
    "        B ElementStart @1960 F=@1993:ElementEnd",
    "          R DefAttribute @1964",
    "          R PropertyWithExtension @1986",
    "        B ElementStart @1994 F=@2210:ElementEnd",
    "          R DefAttribute @1998",
    "          R PropertyWithConverter @2025",
    "          R PropertyWithConverter @2035",
    "          B PropertyListStart @2045 F=@2209:PropertyListEnd",
    "            B ElementStart @2048 F=@2208:ElementEnd",
    "              R DefAttribute @2052",
    "              B ElementStart @2082 F=@2122:ElementEnd",
    "                R DefAttribute @2086",
    "                R PropertyWithExtension @2107",
    "                R PropertyWithConverter @2114",
    "              B ElementStart @2123 F=@2164:ElementEnd",
    "                R DefAttribute @2127",
    "                R PropertyWithExtension @2148",
    "                R PropertyWithConverter @2155",
    "              B ElementStart @2165 F=@2207:ElementEnd",
    "                R DefAttribute @2169",
    "                R PropertyWithExtension @2190",
    "                R PropertyWithConverter @2197",
    "        B ElementStart @2211 F=@2427:ElementEnd",
    "          R DefAttribute @2215",
    "          R PropertyWithConverter @2242",
    "          R PropertyWithConverter @2252",
    "          B PropertyListStart @2262 F=@2426:PropertyListEnd",
    "            B ElementStart @2265 F=@2425:ElementEnd",
    "              R DefAttribute @2269",
    "              B ElementStart @2299 F=@2339:ElementEnd",
    "                R DefAttribute @2303",
    "                R PropertyWithExtension @2324",
    "                R PropertyWithConverter @2331",
    "              B ElementStart @2340 F=@2381:ElementEnd",
    "                R DefAttribute @2344",
    "                R PropertyWithExtension @2365",
    "                R PropertyWithConverter @2372",
    "              B ElementStart @2382 F=@2424:ElementEnd",
    "                R DefAttribute @2386",
    "                R PropertyWithExtension @2407",
    "                R PropertyWithConverter @2414",
    "        B ElementStart @2428 F=@2629:ElementEnd",
    "          R DefAttribute @2432",
    "          R PropertyWithConverter @2459",
    "          R PropertyWithConverter @2485",
    "          B PropertyListStart @2511 F=@2628:PropertyListEnd",
    "            B ElementStart @2514 F=@2570:ElementEnd",
    "              R DefAttribute @2518",
    "              R PropertyWithConverter @2539",
    "              R PropertyWithConverter @2554",
    "            B ElementStart @2571 F=@2627:ElementEnd",
    "              R DefAttribute @2575",
    "              R PropertyWithConverter @2596",
    "              R PropertyWithConverter @2611",
    "        B ElementStart @2630 F=@2722:ElementEnd",
    "          R DefAttribute @2634",
    "          R PropertyWithConverter @2647",
    "          R PropertyWithConverter @2655",
    "          R ContentProperty @2663",
    "          B ElementStart @2666 F=@2721:ElementEnd",
    "            R DefAttribute @2670",
    "            R PropertyCustom @2681",
    "            R PropertyWithStaticResourceId @2716",
    "        B ElementStart @2723 F=@2815:ElementEnd",
    "          R DefAttribute @2727",
    "          R PropertyWithConverter @2740",
    "          R PropertyWithConverter @2748",
    "          R ContentProperty @2756",
    "          B ElementStart @2759 F=@2814:ElementEnd",
    "            R DefAttribute @2763",
    "            R PropertyCustom @2774",
    "            R PropertyWithStaticResourceId @2809",
    "        B ElementStart @2816 F=@3242:ElementEnd",
    "          R DefAttribute @2820",
    "          R PropertyTypeReference @2832",
    "          R ContentProperty @2837",
    "          B ElementStart @2840 F=@2920:ElementEnd",
    "            R DefAttribute @2844",
    "            R PropertyCustom @2857",
    "            B PropertyComplexStart @2865 F=@2919:PropertyComplexEnd",
    "              B ElementStart @2868 F=@2918:ElementEnd",
    "                R PropertyWithConverter @2872",
    "                B PropertyComplexStart @2889 F=@2917:PropertyComplexEnd",
    "                  B ElementStart @2892 F=@2916:ElementEnd",
    "                    B ConstructorParametersStart @2896 F=@2915:ConstructorParametersEnd",
    "                      R Text @2897",
    "          B ElementStart @2921 F=@2999:ElementEnd",
    "            R DefAttribute @2925",
    "            R PropertyCustom @2938",
    "            B PropertyComplexStart @2946 F=@2998:PropertyComplexEnd",
    "              B ElementStart @2949 F=@2997:ElementEnd",
    "                R PropertyWithConverter @2953",
    "                B PropertyComplexStart @2968 F=@2996:PropertyComplexEnd",
    "                  B ElementStart @2971 F=@2995:ElementEnd",
    "                    B ConstructorParametersStart @2975 F=@2994:ConstructorParametersEnd",
    "                      R Text @2976",
    "          B ElementStart @3000 F=@3079:ElementEnd",
    "            R DefAttribute @3004",
    "            R PropertyCustom @3017",
    "            B PropertyComplexStart @3025 F=@3078:PropertyComplexEnd",
    "              B ElementStart @3028 F=@3077:ElementEnd",
    "                R PropertyWithConverter @3032",
    "                B PropertyComplexStart @3048 F=@3076:PropertyComplexEnd",
    "                  B ElementStart @3051 F=@3075:ElementEnd",
    "                    B ConstructorParametersStart @3055 F=@3074:ConstructorParametersEnd",
    "                      R Text @3056",
    "          B ElementStart @3080 F=@3160:ElementEnd",
    "            R DefAttribute @3084",
    "            R PropertyCustom @3097",
    "            B PropertyComplexStart @3105 F=@3159:PropertyComplexEnd",
    "              B ElementStart @3108 F=@3158:ElementEnd",
    "                R PropertyWithConverter @3112",
    "                B PropertyComplexStart @3129 F=@3157:PropertyComplexEnd",
    "                  B ElementStart @3132 F=@3156:ElementEnd",
    "                    B ConstructorParametersStart @3136 F=@3155:ConstructorParametersEnd",
    "                      R Text @3137",
    "          B ElementStart @3161 F=@3241:ElementEnd",
    "            R DefAttribute @3165",
    "            R PropertyCustom @3178",
    "            B PropertyComplexStart @3186 F=@3240:PropertyComplexEnd",
    "              B ElementStart @3189 F=@3239:ElementEnd",
    "                R PropertyWithConverter @3193",
    "                B PropertyComplexStart @3210 F=@3238:PropertyComplexEnd",
    "                  B ElementStart @3213 F=@3237:ElementEnd",
    "                    B ConstructorParametersStart @3217 F=@3236:ConstructorParametersEnd",
    "                      R Text @3218",
    "        B ElementStart @3243 F=@4626:ElementEnd",
    "          R DefAttribute @3247",
    "          R PropertyTypeReference @3260",
    "          R ContentProperty @3265",
    "          B ElementStart @3268 F=@3308:ElementEnd",
    "            R DefAttribute @3272",
    "            R PropertyCustom @3287",
    "            R PropertyWithConverter @3295",
    "          B ElementStart @3309 F=@3349:ElementEnd",
    "            R DefAttribute @3313",
    "            R PropertyCustom @3328",
    "            R PropertyWithConverter @3336",
    "          B ElementStart @3350 F=@3385:ElementEnd",
    "            R DefAttribute @3354",
    "            R PropertyCustom @3369",
    "            R PropertyWithConverter @3377",
    "          B ElementStart @3386 F=@3422:ElementEnd",
    "            R DefAttribute @3390",
    "            R PropertyCustom @3405",
    "            R PropertyWithConverter @3413",
    "          B ElementStart @3423 F=@3459:ElementEnd",
    "            R DefAttribute @3427",
    "            R PropertyCustom @3442",
    "            R PropertyWithConverter @3450",
    "          B ElementStart @3460 F=@3495:ElementEnd",
    "            R DefAttribute @3464",
    "            R PropertyCustom @3479",
    "            R PropertyWithConverter @3487",
    "          B ElementStart @3496 F=@3531:ElementEnd",
    "            R DefAttribute @3500",
    "            R PropertyCustom @3515",
    "            R PropertyWithConverter @3523",
    "          B ElementStart @3532 F=@3570:ElementEnd",
    "            R DefAttribute @3536",
    "            R PropertyCustom @3551",
    "            R PropertyCustom @3559",
    "          B ElementStart @3571 F=@4625:ElementEnd",
    "            R DefAttribute @3575",
    "            R PropertyCustom @3590",
    "            B PropertyComplexStart @3598 F=@4624:PropertyComplexEnd",
    "              B ElementStart @3601 F=@4623:ElementEnd",
    "                R DefAttribute @3605",
    "                R PropertyTypeReference @3628",
    "                R ContentProperty @3633",
    "                B ElementStart @3636 F=@3822:ElementEnd",
    "                  R DefAttribute @3640",
    "                  R PropertyCustom @3654",
    "                  R PropertyWithExtension @3665",
    "                  R PropertyWithExtension @3672",
    "                  R ContentProperty @3679",
    "                  B ElementStart @3682 F=@3821:ElementEnd",
    "                    R DefAttribute @3686",
    "                    R PropertyWithExtension @3698",
    "                    R PropertyWithExtension @3705",
    "                    R ContentProperty @3712",
    "                    B ElementStart @3715 F=@3820:ElementEnd",
    "                      R PropertyWithConverter @3719",
    "                      R DefAttribute @3736",
    "                      R PropertyWithConverter @3750",
    "                      R PropertyCustom @3758",
    "                      R ContentProperty @3769",
    "                      B ElementStart @3772 F=@3819:ElementEnd",
    "                        R PropertyWithConverter @3776",
    "                        R DefAttribute @3796",
    "                B PropertyListStart @3823 F=@4622:PropertyListEnd",
    "                  B ElementStart @3826 F=@3942:ElementEnd",
    "                    R DefAttribute @3830",
    "                    R PropertyCustom @3852",
    "                    R PropertyCustom @3860",
    "                    R ContentProperty @3867",
    "                    B ElementStart @3870 F=@3941:ElementEnd",
    "                      R DefAttribute @3874",
    "                      R PropertyWithConverter @3895",
    "                      R PropertyCustom @3915",
    "                      R PropertyWithConverter @3931",
    "                  B ElementStart @3943 F=@4092:ElementEnd",
    "                    R DefAttribute @3947",
    "                    R PropertyCustom @3962",
    "                    R PropertyCustom @3982",
    "                    R ContentProperty @3989",
    "                    B ElementStart @3992 F=@4041:ElementEnd",
    "                      R DefAttribute @3996",
    "                      R PropertyWithConverter @4011",
    "                      R PropertyWithStaticResourceId @4028",
    "                      R PropertyCustom @4033",
    "                    B ElementStart @4042 F=@4091:ElementEnd",
    "                      R DefAttribute @4046",
    "                      R PropertyWithConverter @4061",
    "                      R PropertyWithStaticResourceId @4078",
    "                      R PropertyCustom @4083",
    "                  B ElementStart @4093 F=@4248:ElementEnd",
    "                    R DefAttribute @4097",
    "                    R PropertyCustom @4112",
    "                    R PropertyCustom @4138",
    "                    R ContentProperty @4145",
    "                    B ElementStart @4148 F=@4197:ElementEnd",
    "                      R DefAttribute @4152",
    "                      R PropertyWithConverter @4167",
    "                      R PropertyWithStaticResourceId @4184",
    "                      R PropertyCustom @4189",
    "                    B ElementStart @4198 F=@4247:ElementEnd",
    "                      R DefAttribute @4202",
    "                      R PropertyWithConverter @4217",
    "                      R PropertyWithStaticResourceId @4234",
    "                      R PropertyCustom @4239",
    "                  B ElementStart @4249 F=@4483:ElementEnd",
    "                    R DefAttribute @4253",
    "                    B PropertyListStart @4272 F=@4379:PropertyListEnd",
    "                      B ElementStart @4275 F=@4323:ElementEnd",
    "                        R DefAttribute @4279",
    "                        R PropertyCustom @4296",
    "                        R PropertyCustom @4316",
    "                      B ElementStart @4324 F=@4378:ElementEnd",
    "                        R DefAttribute @4328",
    "                        R PropertyCustom @4345",
    "                        R PropertyCustom @4371",
    "                    R ContentProperty @4380",
    "                    B ElementStart @4383 F=@4432:ElementEnd",
    "                      R DefAttribute @4387",
    "                      R PropertyWithConverter @4402",
    "                      R PropertyWithStaticResourceId @4419",
    "                      R PropertyCustom @4424",
    "                    B ElementStart @4433 F=@4482:ElementEnd",
    "                      R DefAttribute @4437",
    "                      R PropertyWithConverter @4452",
    "                      R PropertyWithStaticResourceId @4469",
    "                      R PropertyCustom @4474",
    "                  B ElementStart @4484 F=@4621:ElementEnd",
    "                    R DefAttribute @4488",
    "                    R PropertyCustom @4503",
    "                    R PropertyCustom @4511",
    "                    R ContentProperty @4518",
    "                    B ElementStart @4521 F=@4570:ElementEnd",
    "                      R DefAttribute @4525",
    "                      R PropertyWithConverter @4540",
    "                      R PropertyWithStaticResourceId @4557",
    "                      R PropertyCustom @4562",
    "                    B ElementStart @4571 F=@4620:ElementEnd",
    "                      R DefAttribute @4575",
    "                      R PropertyWithConverter @4590",
    "                      R PropertyWithStaticResourceId @4607",
    "                      R PropertyCustom @4612",
    "        B ElementStart @4627 F=@4928:ElementEnd",
    "          R DefAttribute @4631",
    "          R PropertyTypeReference @4643",
    "          B PropertyComplexStart @4648 F=@4656:PropertyComplexEnd",
    "            B ElementStart @4651 F=@4655:ElementEnd",
    "          R ContentProperty @4657",
    "          B ElementStart @4660 F=@4694:ElementEnd",
    "            R DefAttribute @4664",
    "            R PropertyCustom @4678",
    "            R PropertyWithConverter @4686",
    "          B ElementStart @4695 F=@4735:ElementEnd",
    "            R DefAttribute @4699",
    "            R PropertyCustom @4713",
    "            R PropertyWithConverter @4721",
    "          B ElementStart @4736 F=@4773:ElementEnd",
    "            R DefAttribute @4740",
    "            R PropertyCustom @4755",
    "            R PropertyWithConverter @4763",
    "          B ElementStart @4774 F=@4814:ElementEnd",
    "            R DefAttribute @4778",
    "            R PropertyCustom @4793",
    "            R PropertyWithConverter @4801",
    "          B ElementStart @4815 F=@4853:ElementEnd",
    "            R DefAttribute @4819",
    "            R PropertyCustom @4834",
    "            R PropertyWithConverter @4842",
    "          B ElementStart @4854 F=@4892:ElementEnd",
    "            R DefAttribute @4858",
    "            R PropertyCustom @4873",
    "            R PropertyCustom @4881",
    "          B ElementStart @4893 F=@4927:ElementEnd",
    "            R DefAttribute @4897",
    "            R PropertyCustom @4912",
    "            R PropertyWithExtension @4920",
    "        B ElementStart @4929 F=@5307:ElementEnd",
    "          R DefAttribute @4933",
    "          R PropertyTypeReference @4945",
    "          B PropertyComplexStart @4950 F=@4958:PropertyComplexEnd",
    "            B ElementStart @4953 F=@4957:ElementEnd",
    "          R ContentProperty @4959",
    "          B ElementStart @4962 F=@4996:ElementEnd",
    "            R DefAttribute @4966",
    "            R PropertyCustom @4980",
    "            R PropertyWithConverter @4988",
    "          B ElementStart @4997 F=@5035:ElementEnd",
    "            R DefAttribute @5001",
    "            R PropertyCustom @5016",
    "            R PropertyCustom @5024",
    "          B ElementStart @5036 F=@5070:ElementEnd",
    "            R DefAttribute @5040",
    "            R PropertyCustom @5054",
    "            R PropertyWithConverter @5062",
    "          B ElementStart @5071 F=@5105:ElementEnd",
    "            R DefAttribute @5075",
    "            R PropertyCustom @5089",
    "            R PropertyWithConverter @5097",
    "          B ElementStart @5106 F=@5143:ElementEnd",
    "            R DefAttribute @5110",
    "            R PropertyCustom @5125",
    "            R PropertyWithConverter @5133",
    "          B ElementStart @5144 F=@5187:ElementEnd",
    "            R DefAttribute @5148",
    "            R PropertyCustom @5162",
    "            R PropertyCustom @5180",
    "          B ElementStart @5188 F=@5228:ElementEnd",
    "            R DefAttribute @5192",
    "            R PropertyCustom @5207",
    "            R PropertyWithConverter @5215",
    "          B ElementStart @5229 F=@5267:ElementEnd",
    "            R DefAttribute @5233",
    "            R PropertyCustom @5248",
    "            R PropertyWithConverter @5256",
    "          B ElementStart @5268 F=@5306:ElementEnd",
    "            R DefAttribute @5272",
    "            R PropertyCustom @5287",
    "            R PropertyCustom @5295",
    "        B ElementStart @5308 F=@7151:ElementEnd",
    "          R DefAttribute @5312",
    "          R PropertyTypeReference @5326",
    "          R ContentProperty @5331",
    "          B ElementStart @5334 F=@5374:ElementEnd",
    "            R DefAttribute @5338",
    "            R PropertyCustom @5353",
    "            R PropertyWithConverter @5361",
    "          B ElementStart @5375 F=@5415:ElementEnd",
    "            R DefAttribute @5379",
    "            R PropertyCustom @5394",
    "            R PropertyWithConverter @5402",
    "          B ElementStart @5416 F=@5451:ElementEnd",
    "            R DefAttribute @5420",
    "            R PropertyCustom @5435",
    "            R PropertyWithConverter @5443",
    "          B ElementStart @5452 F=@5488:ElementEnd",
    "            R DefAttribute @5456",
    "            R PropertyCustom @5471",
    "            R PropertyWithConverter @5479",
    "          B ElementStart @5489 F=@5525:ElementEnd",
    "            R DefAttribute @5493",
    "            R PropertyCustom @5508",
    "            R PropertyWithConverter @5516",
    "          B ElementStart @5526 F=@5567:ElementEnd",
    "            R DefAttribute @5530",
    "            R PropertyCustom @5545",
    "            R PropertyWithConverter @5553",
    "          B ElementStart @5568 F=@5603:ElementEnd",
    "            R DefAttribute @5572",
    "            R PropertyCustom @5587",
    "            R PropertyWithConverter @5595",
    "          B ElementStart @5604 F=@5642:ElementEnd",
    "            R DefAttribute @5608",
    "            R PropertyCustom @5623",
    "            R PropertyCustom @5631",
    "          B ElementStart @5643 F=@7150:ElementEnd",
    "            R DefAttribute @5647",
    "            R PropertyCustom @5662",
    "            B PropertyComplexStart @5670 F=@7149:PropertyComplexEnd",
    "              B ElementStart @5673 F=@7148:ElementEnd",
    "                R DefAttribute @5677",
    "                R PropertyTypeReference @5700",
    "                R ContentProperty @5705",
    "                B ElementStart @5708 F=@6333:ElementEnd",
    "                  R DefAttribute @5712",
    "                  R PropertyCustom @5726",
    "                  R PropertyWithExtension @5737",
    "                  R PropertyWithExtension @5744",
    "                  R ContentProperty @5751",
    "                  B ElementStart @5754 F=@6332:ElementEnd",
    "                    R DefAttribute @5758",
    "                    R PropertyWithExtension @5770",
    "                    R PropertyWithExtension @5777",
    "                    R ContentProperty @5784",
    "                    B ElementStart @5787 F=@5961:ElementEnd",
    "                      R PropertyWithConverter @5791",
    "                      R DefAttribute @5808",
    "                      R PropertyWithConverter @5822",
    "                      R PropertyCustom @5830",
    "                      R ContentProperty @5841",
    "                      B ElementStart @5844 F=@5960:ElementEnd",
    "                        R DefAttribute @5848",
    "                        R PropertyWithConverter @5861",
    "                        R PropertyWithConverter @5869",
    "                        R ContentProperty @5877",
    "                        B ElementStart @5880 F=@5959:ElementEnd",
    "                          R PropertyWithConverter @5884",
    "                          R DefAttribute @5906",
    "                          R PropertyWithExtension @5917",
    "                          R PropertyCustom @5924",
    "                    B ElementStart @5962 F=@6331:ElementEnd",
    "                      R PropertyWithConverter @5966",
    "                      R DefAttribute @5985",
    "                      R PropertyCustom @5997",
    "                      R PropertyWithConverter @6004",
    "                      R PropertyWithConverter @6017",
    "                      R PropertyCustom @6025",
    "                      R PropertyWithExtension @6032",
    "                      B PropertyComplexStart @6039 F=@6096:PropertyComplexEnd",
    "                        B ElementStart @6042 F=@6095:ElementEnd",
    "                          R PropertyWithConverter @6046",
    "                          B PropertyComplexStart @6066 F=@6094:PropertyComplexEnd",
    "                            B ElementStart @6069 F=@6093:ElementEnd",
    "                              B ConstructorParametersStart @6073 F=@6092:ConstructorParametersEnd",
    "                                R Text @6074",
    "                      R ContentProperty @6097",
    "                      B ElementStart @6100 F=@6330:ElementEnd",
    "                        R PropertyWithConverter @6104",
    "                        R DefAttribute @6118",
    "                        R ContentProperty @6130",
    "                        B ElementStart @6133 F=@6197:ElementEnd",
    "                          R PropertyWithConverter @6137",
    "                          R DefAttribute @6157",
    "                          R PropertyWithExtension @6175",
    "                          R PropertyWithConverter @6182",
    "                          R PropertyWithExtension @6190",
    "                        B ElementStart @6198 F=@6329:ElementEnd",
    "                          R DefAttribute @6202",
    "                          R PropertyWithConverter @6221",
    "                          R PropertyCustom @6229",
    "                          B PropertyComplexStart @6236 F=@6279:PropertyComplexEnd",
    "                            B ElementStart @6239 F=@6278:ElementEnd",
    "                              B ConstructorParametersStart @6243 F=@6277:ConstructorParametersEnd",
    "                                B ElementStart @6244 F=@6276:ElementEnd",
    "                                  R PropertyTypeReference @6248",
    "                                  R PropertyWithConverter @6253",
    "                          R ContentProperty @6280",
    "                          B ElementStart @6283 F=@6328:ElementEnd",
    "                            R DefAttribute @6287",
    "                            R PropertyWithConverter @6308",
    "                            R PropertyWithConverter @6316",
    "                B PropertyListStart @6334 F=@7147:PropertyListEnd",
    "                  B ElementStart @6337 F=@6457:ElementEnd",
    "                    R DefAttribute @6341",
    "                    R PropertyCustom @6364",
    "                    R PropertyCustom @6372",
    "                    R ContentProperty @6379",
    "                    B ElementStart @6382 F=@6456:ElementEnd",
    "                      R DefAttribute @6386",
    "                      R PropertyWithConverter @6408",
    "                      R PropertyCustom @6430",
    "                      R PropertyWithConverter @6446",
    "                  B ElementStart @6458 F=@6607:ElementEnd",
    "                    R DefAttribute @6462",
    "                    R PropertyCustom @6477",
    "                    R PropertyCustom @6497",
    "                    R ContentProperty @6504",
    "                    B ElementStart @6507 F=@6556:ElementEnd",
    "                      R DefAttribute @6511",
    "                      R PropertyWithConverter @6526",
    "                      R PropertyWithStaticResourceId @6543",
    "                      R PropertyCustom @6548",
    "                    B ElementStart @6557 F=@6606:ElementEnd",
    "                      R DefAttribute @6561",
    "                      R PropertyWithConverter @6576",
    "                      R PropertyWithStaticResourceId @6593",
    "                      R PropertyCustom @6598",
    "                  B ElementStart @6608 F=@6763:ElementEnd",
    "                    R DefAttribute @6612",
    "                    R PropertyCustom @6627",
    "                    R PropertyCustom @6653",
    "                    R ContentProperty @6660",
    "                    B ElementStart @6663 F=@6712:ElementEnd",
    "                      R DefAttribute @6667",
    "                      R PropertyWithConverter @6682",
    "                      R PropertyWithStaticResourceId @6699",
    "                      R PropertyCustom @6704",
    "                    B ElementStart @6713 F=@6762:ElementEnd",
    "                      R DefAttribute @6717",
    "                      R PropertyWithConverter @6732",
    "                      R PropertyWithStaticResourceId @6749",
    "                      R PropertyCustom @6754",
    "                  B ElementStart @6764 F=@6998:ElementEnd",
    "                    R DefAttribute @6768",
    "                    B PropertyListStart @6787 F=@6894:PropertyListEnd",
    "                      B ElementStart @6790 F=@6838:ElementEnd",
    "                        R DefAttribute @6794",
    "                        R PropertyCustom @6811",
    "                        R PropertyCustom @6831",
    "                      B ElementStart @6839 F=@6893:ElementEnd",
    "                        R DefAttribute @6843",
    "                        R PropertyCustom @6860",
    "                        R PropertyCustom @6886",
    "                    R ContentProperty @6895",
    "                    B ElementStart @6898 F=@6947:ElementEnd",
    "                      R DefAttribute @6902",
    "                      R PropertyWithConverter @6917",
    "                      R PropertyWithStaticResourceId @6934",
    "                      R PropertyCustom @6939",
    "                    B ElementStart @6948 F=@6997:ElementEnd",
    "                      R DefAttribute @6952",
    "                      R PropertyWithConverter @6967",
    "                      R PropertyWithStaticResourceId @6984",
    "                      R PropertyCustom @6989",
    "                  B ElementStart @6999 F=@7146:ElementEnd",
    "                    R DefAttribute @7003",
    "                    R PropertyCustom @7018",
    "                    R PropertyCustom @7036",
    "                    R ContentProperty @7043",
    "                    B ElementStart @7046 F=@7095:ElementEnd",
    "                      R DefAttribute @7050",
    "                      R PropertyWithConverter @7065",
    "                      R PropertyWithStaticResourceId @7082",
    "                      R PropertyCustom @7087",
    "                    B ElementStart @7096 F=@7145:ElementEnd",
    "                      R DefAttribute @7100",
    "                      R PropertyWithConverter @7115",
    "                      R PropertyWithStaticResourceId @7132",
    "                      R PropertyCustom @7137",
    "    R ContentProperty @7154",
    "    B ElementStart @7157 F=@9455:ElementEnd",
    "      R ConnectionId @7161",
    "      R PropertyWithConverter @7166",
    "      R DefAttribute @7190",
    "      R PropertyWithExtension @7212",
    "      R AttributeInfo @7219",
    "      R PropertyCustom @7246",
    "      R PropertyWithConverter @7253",
    "      R PropertyWithConverter @7261",
    "      R PropertyWithConverter @7269",
    "      B PropertyComplexStart @7283 F=@7532:PropertyComplexEnd",
    "        B ElementStart @7286 F=@7531:ElementEnd",
    "          R DefAttribute @7290",
    "          R PropertyWithConverter @7317",
    "          R PropertyWithConverter @7327",
    "          B PropertyListStart @7337 F=@7530:PropertyListEnd",
    "            B ElementStart @7340 F=@7529:ElementEnd",
    "              R DefAttribute @7344",
    "              B ElementStart @7374 F=@7414:ElementEnd",
    "                R DefAttribute @7378",
    "                R PropertyWithExtension @7399",
    "                R PropertyWithConverter @7406",
    "              B ElementStart @7415 F=@7487:ElementEnd",
    "                R DefAttribute @7419",
    "                R ConnectionId @7440",
    "                R DefAttribute @7445",
    "                R PropertyWithExtension @7472",
    "                R PropertyWithConverter @7479",
    "              B ElementStart @7488 F=@7528:ElementEnd",
    "                R DefAttribute @7492",
    "                R PropertyWithExtension @7513",
    "                R PropertyWithConverter @7520",
    "      R AttributeInfo @7533",
    "      B PropertyListStart @7549 F=@8039:PropertyListEnd",
    "        B ElementStart @7552 F=@8038:ElementEnd",
    "          R DefAttribute @7556",
    "          R AttributeInfo @7575",
    "          R PropertyWithConverter @7594",
    "          R AttributeInfo @7617",
    "          R PropertyWithConverter @7635",
    "          R ContentProperty @7653",
    "          B ElementStart @7656 F=@8037:ElementEnd",
    "            R DefAttribute @7660",
    "            R ContentProperty @7682",
    "            B ElementStart @7685 F=@8036:ElementEnd",
    "              R DefAttribute @7689",
    "              R ContentProperty @7706",
    "              B ElementStart @7709 F=@7907:ElementEnd",
    "                R DefAttribute @7713",
    "                R AttributeInfo @7734",
    "                R PropertyWithConverter @7752",
    "                R AttributeInfo @7781",
    "                R PropertyWithConverter @7803",
    "                R AttributeInfo @7815",
    "                R PropertyWithExtension @7827",
    "                R AttributeInfo @7834",
    "                R PropertyWithExtension @7844",
    "                R AttributeInfo @7851",
    "                R PropertyWithConverter @7867",
    "                R AttributeInfo @7881",
    "                R PropertyCustom @7900",
    "              B ElementStart @7908 F=@8035:ElementEnd",
    "                R DefAttribute @7912",
    "                R PropertyWithConverter @7934",
    "                R PropertyWithConverter @7963",
    "                R AttributeInfo @7976",
    "                R PropertyWithConverter @7988",
    "                R AttributeInfo @7996",
    "                R PropertyWithConverter @8006",
    "                R PropertyWithConverter @8014",
    "                R PropertyCustom @8028",
    "      R ContentProperty @8040",
    "      B ElementStart @8043 F=@9454:ElementEnd",
    "        R DefAttribute @8047",
    "        R AttributeInfo @8066",
    "        R PropertyWithConverter @8085",
    "        R ContentProperty @8102",
    "        B ElementStart @8105 F=@8473:ElementEnd",
    "          R ConnectionId @8109",
    "          R AttributeInfo @8114",
    "          R PropertyWithConverter @8126",
    "          R DefAttribute @8148",
    "          R PropertyWithConverter @8168",
    "          R PropertyCustom @8181",
    "          R ContentProperty @8192",
    "          B ElementStart @8195 F=@8293:ElementEnd",
    "            R ConnectionId @8199",
    "            R AttributeInfo @8204",
    "            R PropertyWithConverter @8216",
    "            R DefAttribute @8236",
    "            R PropertyWithConverter @8254",
    "            R ContentProperty @8267",
    "            R Text @8270",
    "          B ElementStart @8294 F=@8472:ElementEnd",
    "            R ConnectionId @8298",
    "            R AttributeInfo @8303",
    "            R PropertyWithConverter @8315",
    "            R DefAttribute @8333",
    "            R AttributeInfo @8349",
    "            R PropertyWithConverter @8366",
    "            R AttributeInfo @8376",
    "            R PropertyWithConverter @8391",
    "            R AttributeInfo @8443",
    "            R PropertyCustom @8465",
    "        B ElementStart @8474 F=@8584:ElementEnd",
    "          R ConnectionId @8478",
    "          R AttributeInfo @8483",
    "          R PropertyWithConverter @8495",
    "          R DefAttribute @8520",
    "          R PropertyCustom @8543",
    "          R PropertyWithConverter @8550",
    "          R PropertyCustom @8570",
    "          R PropertyWithExtension @8577",
    "        B ElementStart @8585 F=@8671:ElementEnd",
    "          R ConnectionId @8589",
    "          R PropertyWithConverter @8594",
    "          R DefAttribute @8615",
    "          R PropertyCustom @8634",
    "          R PropertyWithConverter @8641",
    "          R PropertyCustom @8657",
    "          R PropertyWithExtension @8664",
    "        B ElementStart @8672 F=@9453:ElementEnd",
    "          R ConnectionId @8676",
    "          R AttributeInfo @8681",
    "          R PropertyWithConverter @8693",
    "          R DefAttribute @8711",
    "          R PropertyCustom @8727",
    "          R AttributeInfo @8734",
    "          R PropertyCustom @8752",
    "          R PropertyWithConverter @8759",
    "          R PropertyCustom @8772",
    "          R PropertyWithConverter @8783",
    "          R PropertyWithConverter @8798",
    "          R ContentProperty @8813",
    "          B ElementStart @8816 F=@9452:ElementEnd",
    "            R ConnectionId @8820",
    "            R AttributeInfo @8825",
    "            R PropertyWithConverter @8837",
    "            R DefAttribute @8859",
    "            R PropertyWithExtension @8879",
    "            R PropertyCustom @8886",
    "            R PropertyWithConverter @8893",
    "            R PropertyCustom @8907",
    "            R PropertyWithConverter @8914",
    "            R PropertyWithConverter @8929",
    "            R ContentProperty @8944",
    "            B ElementStart @8947 F=@9071:ElementEnd",
    "              R ConnectionId @8951",
    "              R PropertyWithConverter @8956",
    "              R DefAttribute @8987",
    "              R AttributeInfo @9016",
    "              R PropertyCustom @9035",
    "              R PropertyWithConverter @9042",
    "            B ElementStart @9072 F=@9156:ElementEnd",
    "              R ConnectionId @9076",
    "              R PropertyWithConverter @9081",
    "              R DefAttribute @9107",
    "              R PropertyCustom @9131",
    "              R PropertyWithConverter @9138",
    "            B ElementStart @9157 F=@9256:ElementEnd",
    "              R ConnectionId @9161",
    "              R PropertyWithConverter @9166",
    "              R DefAttribute @9197",
    "              R PropertyCustom @9226",
    "              R PropertyWithConverter @9233",
    "            B ElementStart @9257 F=@9350:ElementEnd",
    "              R ConnectionId @9261",
    "              R PropertyWithConverter @9266",
    "              R DefAttribute @9295",
    "              R PropertyCustom @9322",
    "              R PropertyWithConverter @9329",
    "            B ElementStart @9351 F=@9451:ElementEnd",
    "              R ConnectionId @9355",
    "              R PropertyWithConverter @9360",
    "              R DefAttribute @9391",
    "              R PropertyCustom @9420",
    "              R PropertyWithConverter @9427",
};
inline constexpr std::size_t kFindToolbarTreeGoldCount = 809;

// The gold block tree over installationerror (357 dump lines).
inline constexpr const char* kInstallationErrorTreeGold[] = {
    "B DocumentStart @28 F=@4661:DocumentEnd",
    "  R AssemblyInfo @35",
    "  R TypeInfo @54",
    "  B ElementStart @114 F=@4660:ElementEnd",
    "    R AssemblyInfo @118",
    "    R AssemblyInfo @201",
    "    R AssemblyInfo @289",
    "    R XmlnsProperty @382",
    "    R AssemblyInfo @451",
    "    R XmlnsProperty @534",
    "    R AttributeInfo @593",
    "    R PropertyWithConverter @609",
    "    R DefAttribute @621",
    "    B PropertyComplexStart @632 F=@842:PropertyComplexEnd",
    "      B ElementStart @635 F=@841:ElementEnd",
    "        R DefAttribute @639",
    "        R AttributeInfo @665",
    "        R PropertyWithConverter @683",
    "        R AttributeInfo @693",
    "        R PropertyWithConverter @709",
    "        R ContentProperty @719",
    "        B ElementStart @722 F=@794:ElementEnd",
    "          R DefAttribute @726",
    "          R AttributeInfo @745",
    "          R PropertyWithConverter @758",
    "          R AttributeInfo @772",
    "          R PropertyWithConverter @786",
    "        B ElementStart @795 F=@840:ElementEnd",
    "          R DefAttribute @799",
    "          R PropertyWithConverter @818",
    "          R PropertyWithConverter @832",
    "    R ContentProperty @843",
    "    B ElementStart @846 F=@4659:ElementEnd",
    "      R DefAttribute @850",
    "      R AttributeInfo @861",
    "      B PropertyListStart @886 F=@1039:PropertyListEnd",
    "        B ElementStart @889 F=@924:ElementEnd",
    "          R DefAttribute @893",
    "          R PropertyWithConverter @916",
    "        B ElementStart @925 F=@963:ElementEnd",
    "          R DefAttribute @929",
    "          R PropertyWithConverter @952",
    "        B ElementStart @964 F=@1002:ElementEnd",
    "          R DefAttribute @968",
    "          R PropertyWithConverter @991",
    "        B ElementStart @1003 F=@1038:ElementEnd",
    "          R DefAttribute @1007",
    "          R PropertyWithConverter @1030",
    "      R AttributeInfo @1040",
    "      B PropertyListStart @1062 F=@1205:PropertyListEnd",
    "        B ElementStart @1065 F=@1098:ElementEnd",
    "          R DefAttribute @1069",
    "          R PropertyWithConverter @1089",
    "        B ElementStart @1099 F=@1134:ElementEnd",
    "          R DefAttribute @1103",
    "          R PropertyWithConverter @1123",
    "        B ElementStart @1135 F=@1170:ElementEnd",
    "          R DefAttribute @1139",
    "          R PropertyWithConverter @1159",
    "        B ElementStart @1171 F=@1204:ElementEnd",
    "          R DefAttribute @1175",
    "          R PropertyWithConverter @1195",
    "      R ContentProperty @1206",
    "      B ElementStart @1209 F=@3348:ElementEnd",
    "        R DefAttribute @1213",
    "        R PropertyWithConverter @1226",
    "        R PropertyWithConverter @1234",
    "        R PropertyWithConverter @1242",
    "        R PropertyWithConverter @1256",
    "        R ContentProperty @1265",
    "        B ElementStart @1268 F=@2213:ElementEnd",
    "          R ConnectionId @1272",
    "          R PropertyWithConverter @1277",
    "          R PropertyWithConverter @1294",
    "          R DefAttribute @1302",
    "          R PropertyWithConverter @1317",
    "          R PropertyWithConverter @1326",
    "          R PropertyWithConverter @1335",
    "          R ContentProperty @1349",
    "          B ElementStart @1352 F=@1754:ElementEnd",
    "            R DefAttribute @1356",
    "            B PropertyComplexStart @1370 F=@1559:PropertyComplexEnd",
    "              B ElementStart @1373 F=@1558:ElementEnd",
    "                R DefAttribute @1377",
    "                R PropertyWithConverter @1404",
    "                R PropertyWithConverter @1414",
    "                B PropertyListStart @1424 F=@1557:PropertyListEnd",
    "                  B ElementStart @1427 F=@1556:ElementEnd",
    "                    R DefAttribute @1431",
    "                    B ElementStart @1460 F=@1508:ElementEnd",
    "                      R DefAttribute @1464",
    "                      R PropertyWithConverter @1484",
    "                      R PropertyWithConverter @1500",
    "                    B ElementStart @1509 F=@1555:ElementEnd",
    "                      R DefAttribute @1513",
    "                      R PropertyWithConverter @1533",
    "                      R PropertyWithConverter @1547",
    "            B PropertyComplexStart @1560 F=@1753:PropertyComplexEnd",
    "              B ElementStart @1563 F=@1752:ElementEnd",
    "                R DefAttribute @1567",
    "                R PropertyWithConverter @1594",
    "                R PropertyWithConverter @1604",
    "                B PropertyListStart @1614 F=@1751:PropertyListEnd",
    "                  B ElementStart @1617 F=@1750:ElementEnd",
    "                    R DefAttribute @1621",
    "                    B ElementStart @1650 F=@1700:ElementEnd",
    "                      R DefAttribute @1654",
    "                      R PropertyWithConverter @1674",
    "                      R PropertyWithConverter @1692",
    "                    B ElementStart @1701 F=@1749:ElementEnd",
    "                      R DefAttribute @1705",
    "                      R PropertyWithConverter @1725",
    "                      R PropertyWithConverter @1741",
    "          B ElementStart @1755 F=@2007:ElementEnd",
    "            R DefAttribute @1759",
    "            R AttributeInfo @1773",
    "            R PropertyWithConverter @1788",
    "            R PropertyCustom @1798",
    "            R PropertyWithConverter @1809",
    "            B PropertyComplexStart @1817 F=@2006:PropertyComplexEnd",
    "              B ElementStart @1820 F=@2005:ElementEnd",
    "                R DefAttribute @1824",
    "                R PropertyWithConverter @1851",
    "                R PropertyWithConverter @1861",
    "                B PropertyListStart @1871 F=@2004:PropertyListEnd",
    "                  B ElementStart @1874 F=@2003:ElementEnd",
    "                    R DefAttribute @1878",
    "                    B ElementStart @1907 F=@1951:ElementEnd",
    "                      R DefAttribute @1911",
    "                      R PropertyWithConverter @1931",
    "                      R PropertyWithConverter @1943",
    "                    B ElementStart @1952 F=@2002:ElementEnd",
    "                      R DefAttribute @1956",
    "                      R PropertyWithConverter @1976",
    "                      R PropertyWithConverter @1994",
    "          B ElementStart @2008 F=@2212:ElementEnd",
    "            R DefAttribute @2012",
    "            R AttributeInfo @2023",
    "            R PropertyWithConverter @2038",
    "            R PropertyWithConverter @2049",
    "            R PropertyWithConverter @2062",
    "            R PropertyWithConverter @2075",
    "            R PropertyCustom @2083",
    "            R AttributeInfo @2094",
    "            R PropertyWithConverter @2120",
    "            R AttributeInfo @2132",
    "            R PropertyWithConverter @2156",
    "            R PropertyCustom @2168",
    "        B ElementStart @2214 F=@3347:ElementEnd",
    "          R DefAttribute @2218",
    "          R PropertyWithConverter @2229",
    "          R PropertyWithConverter @2237",
    "          R PropertyWithConverter @2246",
    "          R PropertyWithConverter @2255",
    "          R AttributeInfo @2269",
    "          R PropertyWithConverter @2280",
    "          R AttributeInfo @2289",
    "          R PropertyWithConverter @2301",
    "          R ContentProperty @2309",
    "          B ElementStart @2312 F=@2714:ElementEnd",
    "            R DefAttribute @2316",
    "            B PropertyComplexStart @2330 F=@2519:PropertyComplexEnd",
    "              B ElementStart @2333 F=@2518:ElementEnd",
    "                R DefAttribute @2337",
    "                R PropertyWithConverter @2364",
    "                R PropertyWithConverter @2374",
    "                B PropertyListStart @2384 F=@2517:PropertyListEnd",
    "                  B ElementStart @2387 F=@2516:ElementEnd",
    "                    R DefAttribute @2391",
    "                    B ElementStart @2420 F=@2468:ElementEnd",
    "                      R DefAttribute @2424",
    "                      R PropertyWithConverter @2444",
    "                      R PropertyWithConverter @2460",
    "                    B ElementStart @2469 F=@2515:ElementEnd",
    "                      R DefAttribute @2473",
    "                      R PropertyWithConverter @2493",
    "                      R PropertyWithConverter @2507",
    "            B PropertyComplexStart @2520 F=@2713:PropertyComplexEnd",
    "              B ElementStart @2523 F=@2712:ElementEnd",
    "                R DefAttribute @2527",
    "                R PropertyWithConverter @2554",
    "                R PropertyWithConverter @2564",
    "                B PropertyListStart @2574 F=@2711:PropertyListEnd",
    "                  B ElementStart @2577 F=@2710:ElementEnd",
    "                    R DefAttribute @2581",
    "                    B ElementStart @2610 F=@2660:ElementEnd",
    "                      R DefAttribute @2614",
    "                      R PropertyWithConverter @2634",
    "                      R PropertyWithConverter @2652",
    "                    B ElementStart @2661 F=@2709:ElementEnd",
    "                      R DefAttribute @2665",
    "                      R PropertyWithConverter @2685",
    "                      R PropertyWithConverter @2701",
    "          B ElementStart @2715 F=@2952:ElementEnd",
    "            R DefAttribute @2719",
    "            R PropertyWithConverter @2733",
    "            R PropertyCustom @2743",
    "            R PropertyWithConverter @2754",
    "            B PropertyComplexStart @2762 F=@2951:PropertyComplexEnd",
    "              B ElementStart @2765 F=@2950:ElementEnd",
    "                R DefAttribute @2769",
    "                R PropertyWithConverter @2796",
    "                R PropertyWithConverter @2806",
    "                B PropertyListStart @2816 F=@2949:PropertyListEnd",
    "                  B ElementStart @2819 F=@2948:ElementEnd",
    "                    R DefAttribute @2823",
    "                    B ElementStart @2852 F=@2896:ElementEnd",
    "                      R DefAttribute @2856",
    "                      R PropertyWithConverter @2876",
    "                      R PropertyWithConverter @2888",
    "                    B ElementStart @2897 F=@2947:ElementEnd",
    "                      R DefAttribute @2901",
    "                      R PropertyWithConverter @2921",
    "                      R PropertyWithConverter @2939",
    "          B ElementStart @2953 F=@3092:ElementEnd",
    "            R DefAttribute @2957",
    "            R PropertyWithConverter @2968",
    "            R PropertyWithConverter @2979",
    "            R PropertyWithConverter @2992",
    "            R PropertyWithConverter @3005",
    "            R PropertyCustom @3013",
    "            R PropertyWithConverter @3024",
    "            R PropertyWithConverter @3036",
    "            R PropertyCustom @3048",
    "          R AttributeInfo @3093",
    "          B PropertyComplexStart @3112 F=@3268:PropertyComplexEnd",
    "            B ElementStart @3115 F=@3267:ElementEnd",
    "              R DefAttribute @3119",
    "              R PropertyWithConverter @3146",
    "              R PropertyWithConverter @3156",
    "              R ContentProperty @3166",
    "              B ElementStart @3169 F=@3213:ElementEnd",
    "                R DefAttribute @3173",
    "                R PropertyWithConverter @3193",
    "                R PropertyWithConverter @3201",
    "              B ElementStart @3214 F=@3266:ElementEnd",
    "                R DefAttribute @3218",
    "                R PropertyWithConverter @3238",
    "                R PropertyWithConverter @3248",
    "          B PropertyComplexStart @3269 F=@3346:PropertyComplexEnd",
    "            B ElementStart @3272 F=@3345:ElementEnd",
    "              R DefAttribute @3276",
    "              R AttributeInfo @3297",
    "              R PropertyWithConverter @3311",
    "              R AttributeInfo @3319",
    "              R PropertyWithConverter @3333",
    "      B ElementStart @3349 F=@4074:ElementEnd",
    "        R DefAttribute @3353",
    "        R PropertyWithConverter @3370",
    "        R PropertyWithConverter @3378",
    "        R AttributeInfo @3386",
    "        B PropertyDictionaryStart @3403 F=@3662:PropertyDictionaryEnd",
    "          R AttributeInfo @3406",
    "          R AttributeInfo @3424",
    "          R AttributeInfo @3440",
    "          B ElementStart @3453 F=@3661:ElementEnd",
    "            R DeferableContentStart @3457",
    "            R DefAttributeKeyType @3462",
    "            B ElementStart @3472 F=@3660:ElementEnd",
    "              R DefAttribute @3476",
    "              R PropertyTypeReference @3488",
    "              R ContentProperty @3493",
    "              B ElementStart @3496 F=@3550:ElementEnd",
    "                R DefAttribute @3500",
    "                R PropertyCustom @3513",
    "                R PropertyWithConverter @3521",
    "              B ElementStart @3551 F=@3587:ElementEnd",
    "                R DefAttribute @3555",
    "                R PropertyCustom @3568",
    "                R PropertyWithConverter @3576",
    "              B ElementStart @3588 F=@3625:ElementEnd",
    "                R DefAttribute @3592",
    "                R PropertyCustom @3605",
    "                R PropertyCustom @3613",
    "              B ElementStart @3626 F=@3659:ElementEnd",
    "                R DefAttribute @3630",
    "                R PropertyCustom @3643",
    "                R PropertyWithConverter @3651",
    "        R ContentProperty @3663",
    "        B ElementStart @3666 F=@3760:ElementEnd",
    "          R ConnectionId @3670",
    "          R PropertyWithConverter @3675",
    "          R DefAttribute @3690",
    "          R PropertyWithConverter @3700",
    "          R PropertyCustom @3711",
    "          R PropertyWithConverter @3726",
    "          R PropertyWithConverter @3736",
    "        B ElementStart @3761 F=@3811:ElementEnd",
    "          R ConnectionId @3765",
    "          R PropertyWithConverter @3770",
    "          R DefAttribute @3781",
    "          R PropertyWithConverter @3790",
    "          R PropertyWithConverter @3800",
    "        B ElementStart @3812 F=@4073:ElementEnd",
    "          R ConnectionId @3816",
    "          R PropertyWithConverter @3821",
    "          R PropertyWithConverter @3842",
    "          R DefAttribute @3856",
    "          R PropertyWithConverter @3871",
    "          R PropertyWithConverter @3881",
    "          R PropertyWithConverter @3904",
    "          R Text @3920",
    "          B ElementStart @3997 F=@4072:ElementEnd",
    "            R ConnectionId @4001",
    "            R AttributeInfo @4006",
    "            R PropertyWithConverter @4018",
    "            R DefAttribute @4041",
    "            R ContentProperty @4062",
    "            R Text @4065",
    "      B ElementStart @4075 F=@4272:ElementEnd",
    "        R ConnectionId @4079",
    "        R PropertyWithConverter @4084",
    "        R DefAttribute @4104",
    "        R PropertyWithConverter @4122",
    "        R PropertyWithConverter @4130",
    "        R PropertyWithConverter @4138",
    "        R PropertyWithConverter @4150",
    "        R PropertyWithConverter @4160",
    "        R PropertyWithConverter @4175",
    "        R PropertyWithConverter @4186",
    "        R ContentProperty @4202",
    "        B ElementStart @4205 F=@4271:ElementEnd",
    "          R DefAttribute @4209",
    "          R PropertyWithConverter @4231",
    "          R Text @4254",
    "      B ElementStart @4273 F=@4455:ElementEnd",
    "        R ConnectionId @4277",
    "        R PropertyWithConverter @4282",
    "        R DefAttribute @4300",
    "        R PropertyWithConverter @4316",
    "        R PropertyWithConverter @4324",
    "        R PropertyWithConverter @4332",
    "        R PropertyWithConverter @4344",
    "        R PropertyWithConverter @4354",
    "        R PropertyWithConverter @4369",
    "        R PropertyWithConverter @4380",
    "        R ContentProperty @4396",
    "        B ElementStart @4399 F=@4454:ElementEnd",
    "          R DefAttribute @4403",
    "          R PropertyWithConverter @4423",
    "          R Text @4446",
    "      B ElementStart @4456 F=@4658:ElementEnd",
    "        R ConnectionId @4460",
    "        R PropertyWithConverter @4465",
    "        R DefAttribute @4486",
    "        R PropertyWithConverter @4505",
    "        R PropertyWithConverter @4513",
    "        R PropertyWithConverter @4521",
    "        R PropertyWithConverter @4533",
    "        R PropertyWithConverter @4543",
    "        R PropertyWithConverter @4558",
    "        R PropertyWithConverter @4569",
    "        R ContentProperty @4585",
    "        B ElementStart @4588 F=@4657:ElementEnd",
    "          R DefAttribute @4592",
    "          R PropertyWithConverter @4609",
    "          R Text @4632",
};
inline constexpr std::size_t kInstallationErrorTreeGoldCount = 357;

// The gold block tree over t_omit (3 dump lines).
inline constexpr const char* kOmitTreeGold[] = {
    "B DocumentStart @28 F=@43:DocumentEnd",
    "  B PropertyListStart @35 F=@null",
    "    B ElementStart @38 F=@42:ElementEnd",
};
inline constexpr std::size_t kOmitTreeGoldCount = 3;

// The gold block tree over t_omit2 (4 dump lines).
inline constexpr const char* kOmit2TreeGold[] = {
    "B DocumentStart @28 F=@46:DocumentEnd",
    "  B PropertyArrayStart @35 F=@null",
    "    B PropertyComplexStart @38 F=@null",
    "      B ElementStart @41 F=@45:ElementEnd",
};
inline constexpr std::size_t kOmit2TreeGoldCount = 4;

// The gold block tree over t_truncated (1 dump lines).
inline constexpr const char* kTruncatedTreeGold[] = {
    "B ElementStart @35 F=@null",
};
inline constexpr std::size_t kTruncatedTreeGoldCount = 1;

// The gold block tree over t_two_docs (2 dump lines).
inline constexpr const char* kTwoDocsTreeGold[] = {
    "B DocumentStart @28 F=@35:DocumentEnd",
    "  B DocumentStart @36 F=@43:DocumentEnd",
};
inline constexpr std::size_t kTwoDocsTreeGoldCount = 2;

} // namespace ILSpy::Tests
