// Copyright (c) 2026 ILSpy Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
// Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

//
// Generated gold tables for the DecompilerSettings tests, extracted from
// ICSharpCode.Decompiler/DecompilerSettings.cs (the repo-HEAD authority) and
// cross-checked against the shipped ilspycmd 11.0 engine (C:/temp-probe/SettingsProbe):
// the defaults, the alias, Clone, the lazy formatting default and the PropertyChanged
// compare-then-set all agree; SetLanguageVersion/GetMinimumRequiredVersion differ where
// the shipped build is newer than this repo (a CSharp1 gating block, the
// switchOnReadOnlySpanChar CSharp11 gating, and the objectOrCollectionInitializers /
// introducePrivateProtectedAccessibility spellings), so the version tables pin the
// repo source verbatim.

#pragma once

#include <cstdint>

namespace ILSpy::Tests {

// The C# property defaults, in C# declaration order (property name, default).
struct SettingsDefaultRow { const char* Name; bool Value; };
inline constexpr SettingsDefaultRow kSettingsDefaults[] = {
	{ "NativeIntegers", true },
	{ "NumericIntPtr", true },
	{ "CovariantReturns", true },
	{ "InitAccessors", true },
	{ "RecordClasses", true },
	{ "RecordStructs", true },
	{ "StructDefaultConstructorsAndFieldInitializers", true },
	{ "WithExpressions", true },
	{ "UsePrimaryConstructorSyntax", true },
	{ "FunctionPointers", true },
	{ "ScopedRef", true },
	{ "RequiredMembers", true },
	{ "SwitchExpressions", true },
	{ "FileScopedNamespaces", true },
	{ "AnonymousMethods", true },
	{ "AnonymousTypes", true },
	{ "UseLambdaSyntax", true },
	{ "ExpressionTrees", true },
	{ "YieldReturn", true },
	{ "Dynamic", true },
	{ "AsyncAwait", true },
	{ "AwaitInCatchFinally", true },
	{ "AsyncEnumerator", true },
	{ "DecimalConstants", true },
	{ "FixedBuffers", true },
	{ "StringConcat", true },
	{ "LiftNullables", true },
	{ "NullPropagation", true },
	{ "AutomaticProperties", true },
	{ "GetterOnlyAutomaticProperties", true },
	{ "AutomaticEvents", true },
	{ "UsingStatement", true },
	{ "UseEnhancedUsing", true },
	{ "AlwaysUseBraces", true },
	{ "ForEachStatement", true },
	{ "ForEachWithGetEnumeratorExtension", true },
	{ "ParamsCollections", true },
	{ "LockStatement", true },
	{ "SwitchStatementOnString", true },
	{ "SparseIntegerSwitch", true },
	{ "UsingDeclarations", true },
	{ "ExtensionMethods", true },
	{ "QueryExpressions", true },
	{ "UseImplicitMethodGroupConversion", true },
	{ "UseObjectCreationOfGenericTypeParameter", true },
	{ "AlwaysCastTargetsOfExplicitInterfaceImplementationCalls", false },
	{ "AlwaysQualifyMemberReferences", false },
	{ "AlwaysShowEnumMemberValues", false },
	{ "UseDebugSymbols", true },
	{ "ArrayInitializers", true },
	{ "ObjectOrCollectionInitializers", true },
	{ "DictionaryInitializers", true },
	{ "ExtensionMethodsInCollectionInitializers", true },
	{ "UseRefLocalsForAccurateOrderOfEvaluation", true },
	{ "RefExtensionMethods", true },
	{ "StringInterpolation", true },
	{ "Utf8StringLiterals", true },
	{ "SwitchOnReadOnlySpanChar", true },
	{ "UnsignedRightShift", true },
	{ "CheckedOperators", true },
	{ "ShowXmlDocumentation", true },
	{ "FoldBraces", false },
	{ "ExpandXmlDocumentationComments", false },
	{ "ExpandMemberDefinitions", false },
	{ "ExpandUsingDeclarations", false },
	{ "DecompileMemberBodies", true },
	{ "UseExpressionBodyForCalculatedGetterOnlyProperties", true },
	{ "OutVariables", true },
	{ "Discards", true },
	{ "IntroduceRefModifiersOnStructs", true },
	{ "IntroduceReadonlyAndInModifiers", true },
	{ "IntroducePrivateProtectedAccessibility", true },
	{ "ReadOnlyMethods", true },
	{ "AsyncUsingAndForEachStatement", true },
	{ "IntroduceUnmanagedConstraint", true },
	{ "StackAllocInitializers", true },
	{ "PatternBasedFixedStatement", true },
	{ "TupleTypes", true },
	{ "ThrowExpressions", true },
	{ "TupleConversions", true },
	{ "TupleComparisons", true },
	{ "NamedArguments", true },
	{ "NonTrailingNamedArguments", true },
	{ "OptionalArguments", true },
	{ "ExpandParamsArguments", true },
	{ "LocalFunctions", true },
	{ "Deconstruction", true },
	{ "PatternMatching", true },
	{ "RecursivePatternMatching", true },
	{ "PatternCombinators", true },
	{ "RelationalPatterns", true },
	{ "StaticLocalFunctions", true },
	{ "Ranges", true },
	{ "NullableReferenceTypes", true },
	{ "ShowDebugInfo", false },
	{ "AssumeArrayLengthFitsIntoInt32", true },
	{ "IntroduceIncrementAndDecrement", true },
	{ "MakeAssignmentExpressions", true },
	{ "RemoveDeadCode", false },
	{ "RemoveDeadStores", false },
	{ "LoadInMemory", false },
	{ "ThrowOnAssemblyResolveErrors", true },
	{ "ApplyWindowsRuntimeProjections", true },
	{ "AutoLoadAssemblyReferences", true },
	{ "ForStatement", true },
	{ "DoWhileStatement", true },
	{ "RefReadOnlyParameters", true },
	{ "UsePrimaryConstructorSyntaxForNonRecordTypes", true },
	{ "InlineArrays", true },
	{ "ExtensionMembers", true },
	{ "FirstClassSpanTypes", true },
	{ "SeparateLocalVariableDeclarations", false },
	{ "UseSdkStyleProjectFormat", true },
	{ "UseNestedDirectoriesForNamespaces", false },
	{ "AggressiveScalarReplacementOfAggregates", false },
	{ "AggressiveInlining", false },
	{ "AlwaysUseGlobal", false },
	{ "AlwaysMoveInitializer", false },
	{ "SortCustomAttributes", false },
	{ "SortSwitchSections", false },
	{ "CheckForOverflowUnderflow", false },
};

// The version-gating: for each version, the properties SetLanguageVersion disables.
// (The union of the blocks strictly newer than the version -- the C# if-ladder fires
// for every block the version falls below.)
struct SettingsVersionRow { const char* Version; const char* Disabled; };
inline constexpr SettingsVersionRow kSettingsVersions[] = {
	{ "CSharp2", "AnonymousTypes,AsyncAwait,AsyncEnumerator,AsyncUsingAndForEachStatement,AutomaticProperties,AwaitInCatchFinally,CheckedOperators,CovariantReturns,Deconstruction,DictionaryInitializers,Discards,Dynamic,ExpressionTrees,ExtensionMembers,ExtensionMethods,ExtensionMethodsInCollectionInitializers,FileScopedNamespaces,FirstClassSpanTypes,ForEachWithGetEnumeratorExtension,FunctionPointers,GetterOnlyAutomaticProperties,InitAccessors,InlineArrays,IntroducePrivateProtectedAccessibility,IntroduceReadonlyAndInModifiers,IntroduceRefModifiersOnStructs,IntroduceUnmanagedConstraint,LocalFunctions,NamedArguments,NativeIntegers,NonTrailingNamedArguments,NullPropagation,NullableReferenceTypes,NumericIntPtr,ObjectOrCollectionInitializers,OptionalArguments,OutVariables,ParamsCollections,PatternBasedFixedStatement,PatternCombinators,PatternMatching,QueryExpressions,Ranges,ReadOnlyMethods,RecordClasses,RecordStructs,RecursivePatternMatching,RefExtensionMethods,RefReadOnlyParameters,RelationalPatterns,RequiredMembers,ScopedRef,StackAllocInitializers,StaticLocalFunctions,StringInterpolation,StructDefaultConstructorsAndFieldInitializers,SwitchExpressions,ThrowExpressions,TupleComparisons,TupleConversions,TupleTypes,UnsignedRightShift,UseEnhancedUsing,UseExpressionBodyForCalculatedGetterOnlyProperties,UseLambdaSyntax,UsePrimaryConstructorSyntax,UsePrimaryConstructorSyntaxForNonRecordTypes,UseRefLocalsForAccurateOrderOfEvaluation,Utf8StringLiterals,WithExpressions" },
	{ "CSharp3", "AsyncAwait,AsyncEnumerator,AsyncUsingAndForEachStatement,AwaitInCatchFinally,CheckedOperators,CovariantReturns,Deconstruction,DictionaryInitializers,Discards,Dynamic,ExtensionMembers,ExtensionMethodsInCollectionInitializers,FileScopedNamespaces,FirstClassSpanTypes,ForEachWithGetEnumeratorExtension,FunctionPointers,GetterOnlyAutomaticProperties,InitAccessors,InlineArrays,IntroducePrivateProtectedAccessibility,IntroduceReadonlyAndInModifiers,IntroduceRefModifiersOnStructs,IntroduceUnmanagedConstraint,LocalFunctions,NamedArguments,NativeIntegers,NonTrailingNamedArguments,NullPropagation,NullableReferenceTypes,NumericIntPtr,OptionalArguments,OutVariables,ParamsCollections,PatternBasedFixedStatement,PatternCombinators,PatternMatching,Ranges,ReadOnlyMethods,RecordClasses,RecordStructs,RecursivePatternMatching,RefExtensionMethods,RefReadOnlyParameters,RelationalPatterns,RequiredMembers,ScopedRef,StackAllocInitializers,StaticLocalFunctions,StringInterpolation,StructDefaultConstructorsAndFieldInitializers,SwitchExpressions,ThrowExpressions,TupleComparisons,TupleConversions,TupleTypes,UnsignedRightShift,UseEnhancedUsing,UseExpressionBodyForCalculatedGetterOnlyProperties,UsePrimaryConstructorSyntax,UsePrimaryConstructorSyntaxForNonRecordTypes,UseRefLocalsForAccurateOrderOfEvaluation,Utf8StringLiterals,WithExpressions" },
	{ "CSharp4", "AsyncAwait,AsyncEnumerator,AsyncUsingAndForEachStatement,AwaitInCatchFinally,CheckedOperators,CovariantReturns,Deconstruction,DictionaryInitializers,Discards,ExtensionMembers,ExtensionMethodsInCollectionInitializers,FileScopedNamespaces,FirstClassSpanTypes,ForEachWithGetEnumeratorExtension,FunctionPointers,GetterOnlyAutomaticProperties,InitAccessors,InlineArrays,IntroducePrivateProtectedAccessibility,IntroduceReadonlyAndInModifiers,IntroduceRefModifiersOnStructs,IntroduceUnmanagedConstraint,LocalFunctions,NativeIntegers,NonTrailingNamedArguments,NullPropagation,NullableReferenceTypes,NumericIntPtr,OutVariables,ParamsCollections,PatternBasedFixedStatement,PatternCombinators,PatternMatching,Ranges,ReadOnlyMethods,RecordClasses,RecordStructs,RecursivePatternMatching,RefExtensionMethods,RefReadOnlyParameters,RelationalPatterns,RequiredMembers,ScopedRef,StackAllocInitializers,StaticLocalFunctions,StringInterpolation,StructDefaultConstructorsAndFieldInitializers,SwitchExpressions,ThrowExpressions,TupleComparisons,TupleConversions,TupleTypes,UnsignedRightShift,UseEnhancedUsing,UseExpressionBodyForCalculatedGetterOnlyProperties,UsePrimaryConstructorSyntax,UsePrimaryConstructorSyntaxForNonRecordTypes,UseRefLocalsForAccurateOrderOfEvaluation,Utf8StringLiterals,WithExpressions" },
	{ "CSharp5", "AsyncEnumerator,AsyncUsingAndForEachStatement,AwaitInCatchFinally,CheckedOperators,CovariantReturns,Deconstruction,DictionaryInitializers,Discards,ExtensionMembers,ExtensionMethodsInCollectionInitializers,FileScopedNamespaces,FirstClassSpanTypes,ForEachWithGetEnumeratorExtension,FunctionPointers,GetterOnlyAutomaticProperties,InitAccessors,InlineArrays,IntroducePrivateProtectedAccessibility,IntroduceReadonlyAndInModifiers,IntroduceRefModifiersOnStructs,IntroduceUnmanagedConstraint,LocalFunctions,NativeIntegers,NonTrailingNamedArguments,NullPropagation,NullableReferenceTypes,NumericIntPtr,OutVariables,ParamsCollections,PatternBasedFixedStatement,PatternCombinators,PatternMatching,Ranges,ReadOnlyMethods,RecordClasses,RecordStructs,RecursivePatternMatching,RefExtensionMethods,RefReadOnlyParameters,RelationalPatterns,RequiredMembers,ScopedRef,StackAllocInitializers,StaticLocalFunctions,StringInterpolation,StructDefaultConstructorsAndFieldInitializers,SwitchExpressions,ThrowExpressions,TupleComparisons,TupleConversions,TupleTypes,UnsignedRightShift,UseEnhancedUsing,UseExpressionBodyForCalculatedGetterOnlyProperties,UsePrimaryConstructorSyntax,UsePrimaryConstructorSyntaxForNonRecordTypes,UseRefLocalsForAccurateOrderOfEvaluation,Utf8StringLiterals,WithExpressions" },
	{ "CSharp6", "AsyncEnumerator,AsyncUsingAndForEachStatement,CheckedOperators,CovariantReturns,Deconstruction,Discards,ExtensionMembers,FileScopedNamespaces,FirstClassSpanTypes,ForEachWithGetEnumeratorExtension,FunctionPointers,InitAccessors,InlineArrays,IntroducePrivateProtectedAccessibility,IntroduceReadonlyAndInModifiers,IntroduceRefModifiersOnStructs,IntroduceUnmanagedConstraint,LocalFunctions,NativeIntegers,NonTrailingNamedArguments,NullableReferenceTypes,NumericIntPtr,OutVariables,ParamsCollections,PatternBasedFixedStatement,PatternCombinators,PatternMatching,Ranges,ReadOnlyMethods,RecordClasses,RecordStructs,RecursivePatternMatching,RefExtensionMethods,RefReadOnlyParameters,RelationalPatterns,RequiredMembers,ScopedRef,StackAllocInitializers,StaticLocalFunctions,StructDefaultConstructorsAndFieldInitializers,SwitchExpressions,ThrowExpressions,TupleComparisons,TupleConversions,TupleTypes,UnsignedRightShift,UseEnhancedUsing,UsePrimaryConstructorSyntax,UsePrimaryConstructorSyntaxForNonRecordTypes,UseRefLocalsForAccurateOrderOfEvaluation,Utf8StringLiterals,WithExpressions" },
	{ "CSharp7", "AsyncEnumerator,AsyncUsingAndForEachStatement,CheckedOperators,CovariantReturns,ExtensionMembers,FileScopedNamespaces,FirstClassSpanTypes,ForEachWithGetEnumeratorExtension,FunctionPointers,InitAccessors,InlineArrays,IntroducePrivateProtectedAccessibility,IntroduceReadonlyAndInModifiers,IntroduceRefModifiersOnStructs,IntroduceUnmanagedConstraint,NativeIntegers,NonTrailingNamedArguments,NullableReferenceTypes,NumericIntPtr,ParamsCollections,PatternBasedFixedStatement,PatternCombinators,Ranges,ReadOnlyMethods,RecordClasses,RecordStructs,RecursivePatternMatching,RefExtensionMethods,RefReadOnlyParameters,RelationalPatterns,RequiredMembers,ScopedRef,StackAllocInitializers,StaticLocalFunctions,StructDefaultConstructorsAndFieldInitializers,SwitchExpressions,TupleComparisons,UnsignedRightShift,UseEnhancedUsing,UsePrimaryConstructorSyntax,UsePrimaryConstructorSyntaxForNonRecordTypes,Utf8StringLiterals,WithExpressions" },
	{ "CSharp7_2", "AsyncEnumerator,AsyncUsingAndForEachStatement,CheckedOperators,CovariantReturns,ExtensionMembers,FileScopedNamespaces,FirstClassSpanTypes,ForEachWithGetEnumeratorExtension,FunctionPointers,InitAccessors,InlineArrays,IntroduceUnmanagedConstraint,NativeIntegers,NullableReferenceTypes,NumericIntPtr,ParamsCollections,PatternBasedFixedStatement,PatternCombinators,Ranges,ReadOnlyMethods,RecordClasses,RecordStructs,RecursivePatternMatching,RefReadOnlyParameters,RelationalPatterns,RequiredMembers,ScopedRef,StackAllocInitializers,StaticLocalFunctions,StructDefaultConstructorsAndFieldInitializers,SwitchExpressions,TupleComparisons,UnsignedRightShift,UseEnhancedUsing,UsePrimaryConstructorSyntax,UsePrimaryConstructorSyntaxForNonRecordTypes,Utf8StringLiterals,WithExpressions" },
	{ "CSharp7_3", "AsyncEnumerator,AsyncUsingAndForEachStatement,CheckedOperators,CovariantReturns,ExtensionMembers,FileScopedNamespaces,FirstClassSpanTypes,ForEachWithGetEnumeratorExtension,FunctionPointers,InitAccessors,InlineArrays,NativeIntegers,NullableReferenceTypes,NumericIntPtr,ParamsCollections,PatternCombinators,Ranges,ReadOnlyMethods,RecordClasses,RecordStructs,RecursivePatternMatching,RefReadOnlyParameters,RelationalPatterns,RequiredMembers,ScopedRef,StaticLocalFunctions,StructDefaultConstructorsAndFieldInitializers,SwitchExpressions,UnsignedRightShift,UseEnhancedUsing,UsePrimaryConstructorSyntax,UsePrimaryConstructorSyntaxForNonRecordTypes,Utf8StringLiterals,WithExpressions" },
	{ "CSharp8_0", "CheckedOperators,CovariantReturns,ExtensionMembers,FileScopedNamespaces,FirstClassSpanTypes,ForEachWithGetEnumeratorExtension,FunctionPointers,InitAccessors,InlineArrays,NativeIntegers,NumericIntPtr,ParamsCollections,PatternCombinators,RecordClasses,RecordStructs,RefReadOnlyParameters,RelationalPatterns,RequiredMembers,ScopedRef,StructDefaultConstructorsAndFieldInitializers,UnsignedRightShift,UsePrimaryConstructorSyntax,UsePrimaryConstructorSyntaxForNonRecordTypes,Utf8StringLiterals,WithExpressions" },
	{ "CSharp9_0", "CheckedOperators,ExtensionMembers,FileScopedNamespaces,FirstClassSpanTypes,InlineArrays,NumericIntPtr,ParamsCollections,RecordStructs,RefReadOnlyParameters,RequiredMembers,ScopedRef,StructDefaultConstructorsAndFieldInitializers,UnsignedRightShift,UsePrimaryConstructorSyntaxForNonRecordTypes,Utf8StringLiterals" },
	{ "CSharp10_0", "CheckedOperators,ExtensionMembers,FirstClassSpanTypes,InlineArrays,NumericIntPtr,ParamsCollections,RefReadOnlyParameters,RequiredMembers,ScopedRef,UnsignedRightShift,UsePrimaryConstructorSyntaxForNonRecordTypes,Utf8StringLiterals" },
	{ "CSharp11_0", "ExtensionMembers,FirstClassSpanTypes,InlineArrays,ParamsCollections,RefReadOnlyParameters,UsePrimaryConstructorSyntaxForNonRecordTypes" },
	{ "CSharp12_0", "ExtensionMembers,FirstClassSpanTypes,ParamsCollections" },
	{ "CSharp13_0", "ExtensionMembers,FirstClassSpanTypes" },
	{ "CSharp14_0", "" },
};

// The minimum required version per property (starting from ctor(CSharp1) with only that
// property enabled). Properties absent from every GetMinimumRequiredVersion statement
// answer CSharp1 -- the three HEAD omissions included.
struct SettingsMinVerRow { const char* Name; const char* Version; };
inline constexpr SettingsMinVerRow kSettingsMinVersions[] = {
	{ "NativeIntegers", "CSharp9_0" },
	{ "NumericIntPtr", "CSharp11_0" },
	{ "CovariantReturns", "CSharp9_0" },
	{ "InitAccessors", "CSharp9_0" },
	{ "RecordClasses", "CSharp9_0" },
	{ "RecordStructs", "CSharp10_0" },
	{ "StructDefaultConstructorsAndFieldInitializers", "CSharp10_0" },
	{ "WithExpressions", "CSharp9_0" },
	{ "UsePrimaryConstructorSyntax", "CSharp9_0" },
	{ "FunctionPointers", "CSharp9_0" },
	{ "ScopedRef", "CSharp11_0" },
	{ "RequiredMembers", "CSharp11_0" },
	{ "SwitchExpressions", "CSharp8_0" },
	{ "FileScopedNamespaces", "CSharp10_0" },
	{ "AnonymousMethods", "CSharp2" },
	{ "AnonymousTypes", "CSharp3" },
	{ "UseLambdaSyntax", "CSharp1" },
	{ "ExpressionTrees", "CSharp3" },
	{ "YieldReturn", "CSharp2" },
	{ "Dynamic", "CSharp4" },
	{ "AsyncAwait", "CSharp5" },
	{ "AwaitInCatchFinally", "CSharp6" },
	{ "AsyncEnumerator", "CSharp8_0" },
	{ "DecimalConstants", "CSharp1" },
	{ "FixedBuffers", "CSharp1" },
	{ "StringConcat", "CSharp1" },
	{ "LiftNullables", "CSharp2" },
	{ "NullPropagation", "CSharp6" },
	{ "AutomaticProperties", "CSharp3" },
	{ "GetterOnlyAutomaticProperties", "CSharp6" },
	{ "AutomaticEvents", "CSharp1" },
	{ "UsingStatement", "CSharp1" },
	{ "UseEnhancedUsing", "CSharp1" },
	{ "AlwaysUseBraces", "CSharp1" },
	{ "ForEachStatement", "CSharp1" },
	{ "ForEachWithGetEnumeratorExtension", "CSharp9_0" },
	{ "ParamsCollections", "CSharp13_0" },
	{ "LockStatement", "CSharp1" },
	{ "SwitchStatementOnString", "CSharp1" },
	{ "SparseIntegerSwitch", "CSharp1" },
	{ "UsingDeclarations", "CSharp1" },
	{ "ExtensionMethods", "CSharp1" },
	{ "QueryExpressions", "CSharp3" },
	{ "UseImplicitMethodGroupConversion", "CSharp2" },
	{ "UseObjectCreationOfGenericTypeParameter", "CSharp2" },
	{ "AlwaysCastTargetsOfExplicitInterfaceImplementationCalls", "CSharp1" },
	{ "AlwaysQualifyMemberReferences", "CSharp1" },
	{ "AlwaysShowEnumMemberValues", "CSharp1" },
	{ "UseDebugSymbols", "CSharp1" },
	{ "ArrayInitializers", "CSharp1" },
	{ "ObjectOrCollectionInitializers", "CSharp3" },
	{ "DictionaryInitializers", "CSharp6" },
	{ "ExtensionMethodsInCollectionInitializers", "CSharp6" },
	{ "UseRefLocalsForAccurateOrderOfEvaluation", "CSharp7" },
	{ "RefExtensionMethods", "CSharp7_2" },
	{ "StringInterpolation", "CSharp6" },
	{ "Utf8StringLiterals", "CSharp11_0" },
	{ "SwitchOnReadOnlySpanChar", "CSharp1" },
	{ "UnsignedRightShift", "CSharp11_0" },
	{ "CheckedOperators", "CSharp11_0" },
	{ "ShowXmlDocumentation", "CSharp1" },
	{ "FoldBraces", "CSharp1" },
	{ "ExpandXmlDocumentationComments", "CSharp1" },
	{ "ExpandMemberDefinitions", "CSharp1" },
	{ "ExpandUsingDeclarations", "CSharp1" },
	{ "DecompileMemberBodies", "CSharp1" },
	{ "UseExpressionBodyForCalculatedGetterOnlyProperties", "CSharp6" },
	{ "OutVariables", "CSharp7" },
	{ "Discards", "CSharp7" },
	{ "IntroduceRefModifiersOnStructs", "CSharp7_2" },
	{ "IntroduceReadonlyAndInModifiers", "CSharp7_2" },
	{ "IntroducePrivateProtectedAccessibility", "CSharp7_2" },
	{ "ReadOnlyMethods", "CSharp8_0" },
	{ "AsyncUsingAndForEachStatement", "CSharp8_0" },
	{ "IntroduceUnmanagedConstraint", "CSharp7_3" },
	{ "StackAllocInitializers", "CSharp7_3" },
	{ "PatternBasedFixedStatement", "CSharp7_3" },
	{ "TupleTypes", "CSharp7" },
	{ "ThrowExpressions", "CSharp7" },
	{ "TupleConversions", "CSharp7" },
	{ "TupleComparisons", "CSharp7_3" },
	{ "NamedArguments", "CSharp4" },
	{ "NonTrailingNamedArguments", "CSharp7_2" },
	{ "OptionalArguments", "CSharp4" },
	{ "ExpandParamsArguments", "CSharp1" },
	{ "LocalFunctions", "CSharp7" },
	{ "Deconstruction", "CSharp7" },
	{ "PatternMatching", "CSharp7" },
	{ "RecursivePatternMatching", "CSharp8_0" },
	{ "PatternCombinators", "CSharp9_0" },
	{ "RelationalPatterns", "CSharp9_0" },
	{ "StaticLocalFunctions", "CSharp8_0" },
	{ "Ranges", "CSharp8_0" },
	{ "NullableReferenceTypes", "CSharp8_0" },
	{ "ShowDebugInfo", "CSharp1" },
	{ "AssumeArrayLengthFitsIntoInt32", "CSharp1" },
	{ "IntroduceIncrementAndDecrement", "CSharp1" },
	{ "MakeAssignmentExpressions", "CSharp1" },
	{ "RemoveDeadCode", "CSharp1" },
	{ "RemoveDeadStores", "CSharp1" },
	{ "LoadInMemory", "CSharp1" },
	{ "ThrowOnAssemblyResolveErrors", "CSharp1" },
	{ "ApplyWindowsRuntimeProjections", "CSharp1" },
	{ "AutoLoadAssemblyReferences", "CSharp1" },
	{ "ForStatement", "CSharp1" },
	{ "DoWhileStatement", "CSharp1" },
	{ "RefReadOnlyParameters", "CSharp12_0" },
	{ "UsePrimaryConstructorSyntaxForNonRecordTypes", "CSharp12_0" },
	{ "InlineArrays", "CSharp12_0" },
	{ "ExtensionMembers", "CSharp14_0" },
	{ "FirstClassSpanTypes", "CSharp14_0" },
	{ "SeparateLocalVariableDeclarations", "CSharp1" },
	{ "UseSdkStyleProjectFormat", "CSharp1" },
	{ "UseNestedDirectoriesForNamespaces", "CSharp1" },
	{ "AggressiveScalarReplacementOfAggregates", "CSharp1" },
	{ "AggressiveInlining", "CSharp1" },
	{ "AlwaysUseGlobal", "CSharp1" },
	{ "AlwaysMoveInitializer", "CSharp1" },
	{ "SortCustomAttributes", "CSharp1" },
	{ "SortSwitchSections", "CSharp1" },
	{ "CheckForOverflowUnderflow", "CSharp1" },
};

} // namespace ILSpy::Tests
