// Copyright (c) 2026 ILSpy Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this
// software and associated documentation files (the "Software"), to deal in the Software
// without restriction, including without limitation the rights to use, copy, modify, merge,
// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
// to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
// FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
// OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

// The MetadataMethod attribute slice's gold fixtures (the TinyNetModule.hpp
// precedent): every expectation pinned against the REAL installed
// ICSharpCode.Decompiler 11.0 (the C:/temp-probe/MmAProbe public-API probe
// driving SimpleCompilation(new PEFile(...)) over the identical local
// fixtures -- mscorlib 4.8, System.dll 4.8, and .NET 10 CoreLib).
//
//   * kGoldMethodCurated: the curated method-attribute matrices -- the full
//     GetAttributes() / GetReturnTypeAttributes() renders and the
//     HasAttribute / GetAttribute drives over hand-picked methods covering
//     every DllImport named-arg arm reachable on the local corpora (the
//     calling-convention / charset / BestFitMapping / ExactSpelling /
//     EntryPoint / PreserveSig / SetLastError / ThrowOnUnmappableChar
//     arms), the PreserveSig / MethodImpl synthetic rows (InternalCall,
//     Synchronized, NoInlining, NoOptimization, the RuntimeAsync bits, the
//     MethodCodeType named arg), the SymbolKind-shape fixtures (a .ctor,
//     the Destructor/interface-Method Finalize pair, an op_ operator), and
//     the return-value marshalling / custom-attribute rows.

#pragma once

#include <cstddef>

namespace ILSpy::Tests::MethodAttrGold {


inline constexpr const char* kGoldMethodCurated[] = {
    R"goldline(C method 0600001A)goldline",
    R"goldline(E 0600001A n=1)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.DllImportAttribute>:ctor=<System.Runtime.InteropServices.DllImportAttribute..ctor>:err=False:F=1:N=1)goldline",
    R"goldline(A0:F0:type=<System.String>:val=str:"kernel32.dll")goldline",
    R"goldline(A0:N0:name=SetLastError:kind=Field:type=<System.Boolean>:val=bool:True)goldline",
    R"goldline(E R:0600001A n=0)goldline",
    R"goldline(C method 0600001D)goldline",
    R"goldline(E 0600001D n=2)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.DllImportAttribute>:ctor=<System.Runtime.InteropServices.DllImportAttribute..ctor>:err=False:F=1:N=1)goldline",
    R"goldline(A0:F0:type=<System.String>:val=str:"kernel32.dll")goldline",
    R"goldline(A0:N0:name=EntryPoint:kind=Field:type=<System.String>:val=str:"LocalAlloc")goldline",
    R"goldline(A1:type=<System.Runtime.ConstrainedExecution.ReliabilityContractAttribute>:ctor=<System.Runtime.ConstrainedExecution.ReliabilityContractAttribute..ctor>:err=False:F=2:N=0)goldline",
    R"goldline(A1:F0:type=<System.Runtime.ConstrainedExecution.Consistency>:val=num:Int32:3)goldline",
    R"goldline(A1:F1:type=<System.Runtime.ConstrainedExecution.Cer>:val=num:Int32:1)goldline",
    R"goldline(E R:0600001D n=0)goldline",
    R"goldline(C method 06000026)goldline",
    R"goldline(E 06000026 n=1)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.DllImportAttribute>:ctor=<System.Runtime.InteropServices.DllImportAttribute..ctor>:err=False:F=1:N=4)goldline",
    R"goldline(A0:F0:type=<System.String>:val=str:"kernel32.dll")goldline",
    R"goldline(A0:N0:name=BestFitMapping:kind=Field:type=<System.Boolean>:val=bool:False)goldline",
    R"goldline(A0:N1:name=CharSet:kind=Field:type=<System.Runtime.InteropServices.CharSet>:val=num:Int32:2)goldline",
    R"goldline(A0:N2:name=ExactSpelling:kind=Field:type=<System.Boolean>:val=bool:True)goldline",
    R"goldline(A0:N3:name=SetLastError:kind=Field:type=<System.Boolean>:val=bool:True)goldline",
    R"goldline(E R:06000026 n=0)goldline",
    R"goldline(C method 06000153)goldline",
    R"goldline(E 06000153 n=1)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.DllImportAttribute>:ctor=<System.Runtime.InteropServices.DllImportAttribute..ctor>:err=False:F=1:N=5)goldline",
    R"goldline(A0:F0:type=<System.String>:val=str:"user32.dll")goldline",
    R"goldline(A0:N0:name=CallingConvention:kind=Field:type=<System.Runtime.InteropServices.CallingConvention>:val=num:Int32:3)goldline",
    R"goldline(A0:N1:name=CharSet:kind=Field:type=<System.Runtime.InteropServices.CharSet>:val=num:Int32:3)goldline",
    R"goldline(A0:N2:name=EntryPoint:kind=Field:type=<System.String>:val=str:"LoadStringW")goldline",
    R"goldline(A0:N3:name=ExactSpelling:kind=Field:type=<System.Boolean>:val=bool:True)goldline",
    R"goldline(A0:N4:name=SetLastError:kind=Field:type=<System.Boolean>:val=bool:True)goldline",
    R"goldline(E R:06000153 n=0)goldline",
    R"goldline(C method 060064C5)goldline",
    R"goldline(E 060064C5 n=4)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.DllImportAttribute>:ctor=<System.Runtime.InteropServices.DllImportAttribute..ctor>:err=False:F=1:N=1)goldline",
    R"goldline(A0:F0:type=<System.String>:val=str:"api-ms-win-core-winrt-string-l1-1-0.dll")goldline",
    R"goldline(A0:N0:name=CallingConvention:kind=Field:type=<System.Runtime.InteropServices.CallingConvention>:val=num:Int32:3)goldline",
    R"goldline(A1:type=<System.Security.SecurityCriticalAttribute>:ctor=<System.Security.SecurityCriticalAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(A2:type=<System.Security.SuppressUnmanagedCodeSecurityAttribute>:ctor=<System.Security.SuppressUnmanagedCodeSecurityAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(A3:type=<System.Runtime.InteropServices.DefaultDllImportSearchPathsAttribute>:ctor=<System.Runtime.InteropServices.DefaultDllImportSearchPathsAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A3:F0:type=<System.Runtime.InteropServices.DllImportSearchPath>:val=num:Int32:2048)goldline",
    R"goldline(E R:060064C5 n=0)goldline",
    R"goldline(C method 0600001B)goldline",
    R"goldline(E 0600001B n=1)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.DllImportAttribute>:ctor=<System.Runtime.InteropServices.DllImportAttribute..ctor>:err=False:F=1:N=2)goldline",
    R"goldline(A0:F0:type=<System.String>:val=str:"kernel32.dll")goldline",
    R"goldline(A0:N0:name=BestFitMapping:kind=Field:type=<System.Boolean>:val=bool:True)goldline",
    R"goldline(A0:N1:name=CharSet:kind=Field:type=<System.Runtime.InteropServices.CharSet>:val=num:Int32:4)goldline",
    R"goldline(E R:0600001B n=0)goldline",
    R"goldline(C method 06002EA4)goldline",
    R"goldline(E 06002EA4 n=4)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.DllImportAttribute>:ctor=<System.Runtime.InteropServices.DllImportAttribute..ctor>:err=False:F=1:N=1)goldline",
    R"goldline(A0:F0:type=<System.String>:val=str:"QCall")goldline",
    R"goldline(A0:N0:name=CharSet:kind=Field:type=<System.Runtime.InteropServices.CharSet>:val=num:Int32:3)goldline",
    R"goldline(A1:type=<System.Runtime.CompilerServices.MethodImplAttribute>:ctor=<System.Runtime.CompilerServices.MethodImplAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A1:F0:type=<System.Runtime.CompilerServices.MethodImplOptions>:val=num:Int32:4096)goldline",
    R"goldline(A2:type=<System.Security.SecurityCriticalAttribute>:ctor=<System.Security.SecurityCriticalAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(A3:type=<System.Security.SuppressUnmanagedCodeSecurityAttribute>:ctor=<System.Security.SuppressUnmanagedCodeSecurityAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(E R:06002EA4 n=1)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.MarshalAsAttribute>:ctor=<System.Runtime.InteropServices.MarshalAsAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A0:F0:type=<System.Runtime.InteropServices.UnmanagedType>:val=num:Int32:2)goldline",
    R"goldline(C method 06005021)goldline",
    R"goldline(E 06005021 n=1)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.DllImportAttribute>:ctor=<System.Runtime.InteropServices.DllImportAttribute..ctor>:err=False:F=1:N=1)goldline",
    R"goldline(A0:F0:type=<System.String>:val=str:"clr.dll")goldline",
    R"goldline(A0:N0:name=PreserveSig:kind=Field:type=<System.Boolean>:val=bool:False)goldline",
    R"goldline(E R:06005021 n=1)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.MarshalAsAttribute>:ctor=<System.Runtime.InteropServices.MarshalAsAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A0:F0:type=<System.Runtime.InteropServices.UnmanagedType>:val=num:Int32:25)goldline",
    R"goldline(H M:pinvoke None=False)goldline",
    R"goldline(H M:pinvoke Serializable=False)goldline",
    R"goldline(H M:pinvoke SpecialName=False)goldline",
    R"goldline(H M:pinvoke Obsolete=False)goldline",
    R"goldline(H M:pinvoke Extension=False)goldline",
    R"goldline(H M:pinvoke CompilerGenerated=False)goldline",
    R"goldline(H M:pinvoke Nullable=False)goldline",
    R"goldline(H M:pinvoke NullableContext=False)goldline",
    R"goldline(H M:pinvoke DllImport=True)goldline",
    R"goldline(H M:pinvoke PreserveSig=False)goldline",
    R"goldline(H M:pinvoke MethodImpl=False)goldline",
    R"goldline(H M:pinvoke PermissionSet=False)goldline",
    R"goldline(H M:pinvoke MarshalAs=False)goldline",
    R"goldline(H M:pinvoke Optional=False)goldline",
    R"goldline(H M:pinvoke DefaultParameterValue=False)goldline",
    R"goldline(G M:pinvoke None null)goldline",
    R"goldline(G M:pinvoke Serializable null)goldline",
    R"goldline(G M:pinvoke SpecialName null)goldline",
    R"goldline(G M:pinvoke Obsolete null)goldline",
    R"goldline(G M:pinvoke Extension null)goldline",
    R"goldline(G M:pinvoke CompilerGenerated null)goldline",
    R"goldline(G M:pinvoke Nullable null)goldline",
    R"goldline(G M:pinvoke NullableContext null)goldline",
    R"goldline(G M:pinvoke DllImport found)goldline",
    R"goldline(GA:type=<System.Runtime.InteropServices.DllImportAttribute>:ctor=<System.Runtime.InteropServices.DllImportAttribute..ctor>:err=False:F=1:N=1)goldline",
    R"goldline(GA:F0:type=<System.String>:val=str:"kernel32.dll")goldline",
    R"goldline(GA:N0:name=SetLastError:kind=Field:type=<System.Boolean>:val=bool:True)goldline",
    R"goldline(G M:pinvoke PreserveSig null)goldline",
    R"goldline(G M:pinvoke MethodImpl null)goldline",
    R"goldline(G M:pinvoke PermissionSet null)goldline",
    R"goldline(G M:pinvoke MarshalAs null)goldline",
    R"goldline(G M:pinvoke Optional null)goldline",
    R"goldline(G M:pinvoke DefaultParameterValue null)goldline",
    R"goldline(C sys method 060040AD)goldline",
    R"goldline(E 060040AD n=1)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.DllImportAttribute>:ctor=<<null>>:err=False:F=1:N=4)goldline",
    R"goldline(A0:F0:type=<System.String>:val=str:"advapi32.dll")goldline",
    R"goldline(A0:N0:name=BestFitMapping:kind=Property:type=<System.Boolean>:val=bool:False)goldline",
    R"goldline(A0:N1:name=CharSet:kind=Property:type=<System.Runtime.InteropServices.CharSet>:val=num:Int32:4)goldline",
    R"goldline(A0:N2:name=SetLastError:kind=Property:type=<System.Boolean>:val=bool:True)goldline",
    R"goldline(A0:N3:name=ThrowOnUnmappableChar:kind=Property:type=<System.Boolean>:val=bool:True)goldline",
    R"goldline(C sys method 060040BA)goldline",
    R"goldline(E 060040BA n=1)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.DllImportAttribute>:ctor=<<null>>:err=False:F=1:N=3)goldline",
    R"goldline(A0:F0:type=<System.String>:val=str:"rasapi32.dll")goldline",
    R"goldline(A0:N0:name=BestFitMapping:kind=Property:type=<System.Boolean>:val=bool:False)goldline",
    R"goldline(A0:N1:name=CharSet:kind=Property:type=<System.Runtime.InteropServices.CharSet>:val=num:Int32:4)goldline",
    R"goldline(A0:N2:name=ThrowOnUnmappableChar:kind=Property:type=<System.Boolean>:val=bool:True)goldline",
    R"goldline(C method 060000EF)goldline",
    R"goldline(E 060000EF n=2)goldline",
    R"goldline(A0:type=<System.Runtime.CompilerServices.MethodImplAttribute>:ctor=<System.Runtime.CompilerServices.MethodImplAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A0:F0:type=<System.Runtime.CompilerServices.MethodImplOptions>:val=num:Int32:4096)goldline",
    R"goldline(A1:type=<System.Security.SecurityCriticalAttribute>:ctor=<System.Security.SecurityCriticalAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(E R:060000EF n=0)goldline",
    R"goldline(C method 06001D8F)goldline",
    R"goldline(E 06001D8F n=3)goldline",
    R"goldline(A0:type=<System.Runtime.CompilerServices.MethodImplAttribute>:ctor=<System.Runtime.CompilerServices.MethodImplAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A0:F0:type=<System.Runtime.CompilerServices.MethodImplOptions>:val=num:Int32:32)goldline",
    R"goldline(A1:type=<System.Security.SecuritySafeCriticalAttribute>:ctor=<System.Security.SecuritySafeCriticalAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(A2:type=<System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute>:ctor=<System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(E R:06001D8F n=0)goldline",
    R"goldline(C method 06004090)goldline",
    R"goldline(E 06004090 n=1)goldline",
    R"goldline(A0:type=<System.Runtime.CompilerServices.MethodImplAttribute>:ctor=<System.Runtime.CompilerServices.MethodImplAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A0:F0:type=<System.Runtime.CompilerServices.MethodImplOptions>:val=num:Int32:72)goldline",
    R"goldline(E R:06004090 n=0)goldline",
    R"goldline(C method 060040EA)goldline",
    R"goldline(E 060040EA n=1)goldline",
    R"goldline(A0:type=<System.Runtime.CompilerServices.MethodImplAttribute>:ctor=<System.Runtime.CompilerServices.MethodImplAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A0:F0:type=<System.Runtime.CompilerServices.MethodImplOptions>:val=num:Int32:64)goldline",
    R"goldline(E R:060040EA n=0)goldline",
    R"goldline(C method 06000007)goldline",
    R"goldline(E 06000007 n=1)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.PreserveSigAttribute>:ctor=<System.Runtime.InteropServices.PreserveSigAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(E R:06000007 n=0)goldline",
    R"goldline(C sys method 06000277)goldline",
    R"goldline(E 06000277 n=1)goldline",
    R"goldline(A0:type=<System.Runtime.CompilerServices.MethodImplAttribute>:ctor=<<null>>:err=False:F=1:N=1)goldline",
    R"goldline(A0:F0:type=<System.Runtime.CompilerServices.MethodImplOptions>:val=num:Int32:4096)goldline",
    R"goldline(A0:N0:name=MethodCodeType:kind=Property:type=<System.Runtime.CompilerServices.MethodCodeType>:val=num:Int32:3)goldline",
    R"goldline(C method 0600054F System.String.Copy)goldline",
    R"goldline(E 0600054F n=1)goldline",
    R"goldline(A0:type=<System.Security.SecuritySafeCriticalAttribute>:ctor=<System.Security.SecuritySafeCriticalAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(E R:0600054F n=0)goldline",
    R"goldline(C method 0600022B System.Object.ToString)goldline",
    R"goldline(E 0600022B n=1)goldline",
    R"goldline(A0:type=<__DynamicallyInvokableAttribute>:ctor=<__DynamicallyInvokableAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(E R:0600022B n=0)goldline",
    R"goldline(C method 0600101F System.Math.Abs)goldline",
    R"goldline(E 0600101F n=2)goldline",
    R"goldline(A0:type=<System.CLSCompliantAttribute>:ctor=<System.CLSCompliantAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A0:F0:type=<System.Boolean>:val=bool:False)goldline",
    R"goldline(A1:type=<__DynamicallyInvokableAttribute>:ctor=<__DynamicallyInvokableAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(E R:0600101F n=0)goldline",
    R"goldline(C method 060004E5)goldline",
    R"goldline(E 060004E5 n=3)goldline",
    R"goldline(A0:type=<System.Runtime.CompilerServices.MethodImplAttribute>:ctor=<System.Runtime.CompilerServices.MethodImplAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A0:F0:type=<System.Runtime.CompilerServices.MethodImplOptions>:val=num:Int32:4096)goldline",
    R"goldline(A1:type=<System.Security.SecurityCriticalAttribute>:ctor=<System.Security.SecurityCriticalAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(A2:type=<System.CLSCompliantAttribute>:ctor=<System.CLSCompliantAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A2:F0:type=<System.Boolean>:val=bool:False)goldline",
    R"goldline(E R:060004E5 n=0)goldline",
    R"goldline(C method 06000231)goldline",
    R"goldline(E 06000231 n=3)goldline",
    R"goldline(A0:type=<System.Runtime.ConstrainedExecution.ReliabilityContractAttribute>:ctor=<System.Runtime.ConstrainedExecution.ReliabilityContractAttribute..ctor>:err=False:F=2:N=0)goldline",
    R"goldline(A0:F0:type=<System.Runtime.ConstrainedExecution.Consistency>:val=num:Int32:3)goldline",
    R"goldline(A0:F1:type=<System.Runtime.ConstrainedExecution.Cer>:val=num:Int32:2)goldline",
    R"goldline(A1:type=<System.Runtime.Versioning.NonVersionableAttribute>:ctor=<System.Runtime.Versioning.NonVersionableAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(A2:type=<__DynamicallyInvokableAttribute>:ctor=<__DynamicallyInvokableAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(E R:06000231 n=0)goldline",
    R"goldline(C method 06000011)goldline",
    R"goldline(E 06000011 n=1)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.PreserveSigAttribute>:ctor=<System.Runtime.InteropServices.PreserveSigAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(E R:06000011 n=0)goldline",
    R"goldline(C method 06000D78)goldline",
    R"goldline(E 06000D78 n=2)goldline",
    R"goldline(A0:type=<System.Security.SecuritySafeCriticalAttribute>:ctor=<System.Security.SecuritySafeCriticalAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(A1:type=<__DynamicallyInvokableAttribute>:ctor=<__DynamicallyInvokableAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(E R:06000D78 n=0)goldline",
    R"goldline(H M:plain None=EXCEPTION:ArgumentNullException:"Value cannot be null. (Parameter 'value')")goldline",
    R"goldline(H M:plain Serializable=False)goldline",
    R"goldline(H M:plain SpecialName=False)goldline",
    R"goldline(H M:plain Obsolete=False)goldline",
    R"goldline(H M:plain Extension=False)goldline",
    R"goldline(H M:plain CompilerGenerated=False)goldline",
    R"goldline(H M:plain Nullable=False)goldline",
    R"goldline(H M:plain NullableContext=False)goldline",
    R"goldline(H M:plain DllImport=False)goldline",
    R"goldline(H M:plain PreserveSig=False)goldline",
    R"goldline(H M:plain MethodImpl=False)goldline",
    R"goldline(H M:plain PermissionSet=False)goldline",
    R"goldline(H M:plain MarshalAs=False)goldline",
    R"goldline(H M:plain Optional=False)goldline",
    R"goldline(H M:plain DefaultParameterValue=False)goldline",
    R"goldline(G M:plain None EXCEPTION:ArgumentNullException:"Value cannot be null. (Parameter 'value')")goldline",
    R"goldline(G M:plain Serializable null)goldline",
    R"goldline(G M:plain SpecialName null)goldline",
    R"goldline(G M:plain Obsolete null)goldline",
    R"goldline(G M:plain Extension null)goldline",
    R"goldline(G M:plain CompilerGenerated null)goldline",
    R"goldline(G M:plain Nullable null)goldline",
    R"goldline(G M:plain NullableContext null)goldline",
    R"goldline(G M:plain DllImport null)goldline",
    R"goldline(G M:plain PreserveSig null)goldline",
    R"goldline(G M:plain MethodImpl null)goldline",
    R"goldline(G M:plain PermissionSet null)goldline",
    R"goldline(G M:plain MarshalAs null)goldline",
    R"goldline(G M:plain Optional null)goldline",
    R"goldline(G M:plain DefaultParameterValue null)goldline",
    R"goldline(C method 06002DFC System.Diagnostics.EventLog.WriteEntry)goldline",
    R"goldline(E 06002DFC n=0)goldline",
    R"goldline(E R:06002DFC n=0)goldline",
    R"goldline(C method 06002DFD System.Diagnostics.EventLog.WriteEntry)goldline",
    R"goldline(E 06002DFD n=0)goldline",
    R"goldline(E R:06002DFD n=0)goldline",
    R"goldline(C method 06002DFE System.Diagnostics.EventLog.WriteEntry)goldline",
    R"goldline(E 06002DFE n=0)goldline",
    R"goldline(E R:06002DFE n=0)goldline",
    R"goldline(C core 060080CA)goldline",
    R"goldline(E 060080CA n=3)goldline",
    R"goldline(A0:type=<System.Runtime.CompilerServices.MethodImplAttribute>:ctor=<System.Runtime.CompilerServices.MethodImplAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A0:F0:type=<System.Runtime.CompilerServices.MethodImplOptions>:val=num:Int32:8)goldline",
    R"goldline(A1:type=<System.Runtime.BypassReadyToRunAttribute>:ctor=<System.Runtime.BypassReadyToRunAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(A2:type=<System.Runtime.Versioning.RequiresPreviewFeaturesAttribute>:ctor=<System.Runtime.Versioning.RequiresPreviewFeaturesAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(E R:060080CA n=0)goldline",
    R"goldline(C core 060080CC)goldline",
    R"goldline(E 060080CC n=3)goldline",
    R"goldline(A0:type=<System.Runtime.CompilerServices.IntrinsicAttribute>:ctor=<System.Runtime.CompilerServices.IntrinsicAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(A1:type=<System.Runtime.BypassReadyToRunAttribute>:ctor=<System.Runtime.BypassReadyToRunAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(A2:type=<System.Runtime.Versioning.RequiresPreviewFeaturesAttribute>:ctor=<System.Runtime.Versioning.RequiresPreviewFeaturesAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(E R:060080CC n=0)goldline",
    R"goldline(C core 060081C6)goldline",
    R"goldline(E 060081C6 n=1)goldline",
    R"goldline(A0:type=<System.Runtime.CompilerServices.MethodImplAttribute>:ctor=<System.Runtime.CompilerServices.MethodImplAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A0:F0:type=<System.Runtime.CompilerServices.MethodImplOptions>:val=num:Int32:512)goldline",
    R"goldline(E R:060081C6 n=0)goldline",
    R"goldline(C core 0600028D)goldline",
    R"goldline(E 0600028D n=0)goldline",
    R"goldline(E R:0600028D n=0)goldline",
    R"goldline(C core 060002C0)goldline",
    R"goldline(E 060002C0 n=0)goldline",
    R"goldline(E R:060002C0 n=0)goldline",
    R"goldline(C core 06000020)goldline",
    R"goldline(E 06000020 n=3)goldline",
    R"goldline(A0:type=<System.Runtime.CompilerServices.MethodImplAttribute>:ctor=<System.Runtime.CompilerServices.MethodImplAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A0:F0:type=<System.Runtime.CompilerServices.MethodImplOptions>:val=num:Int32:8)goldline",
    R"goldline(A1:type=<System.Runtime.InteropServices.LibraryImportAttribute>:ctor=<System.Runtime.InteropServices.LibraryImportAttribute..ctor>:err=False:F=1:N=2)goldline",
    R"goldline(A1:F0:type=<System.String>:val=str:"System.Globalization.Native")goldline",
    R"goldline(A1:N0:name=EntryPoint:kind=Property:type=<System.String>:val=str:"GlobalizationNative_StartsWith")goldline",
    R"goldline(A1:N1:name=StringMarshalling:kind=Property:type=<System.Runtime.InteropServices.StringMarshalling>:val=num:Int32:2)goldline",
    R"goldline(A2:type=<System.CodeDom.Compiler.GeneratedCodeAttribute>:ctor=<System.CodeDom.Compiler.GeneratedCodeAttribute..ctor>:err=False:F=2:N=0)goldline",
    R"goldline(A2:F0:type=<System.String>:val=str:"Microsoft.Interop.LibraryImportGenerator")goldline",
    R"goldline(A2:F1:type=<System.String>:val=str:"10.0.14.23019")goldline",
    R"goldline(E R:06000020 n=1)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.MarshalAsAttribute>:ctor=<System.Runtime.InteropServices.MarshalAsAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A0:F0:type=<System.Runtime.InteropServices.UnmanagedType>:val=num:Int32:2)goldline",
    R"goldline(C core 0600030F)goldline",
    R"goldline(E 0600030F n=2)goldline",
    R"goldline(A0:type=<System.Runtime.CompilerServices.MethodImplAttribute>:ctor=<System.Runtime.CompilerServices.MethodImplAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A0:F0:type=<System.Runtime.CompilerServices.MethodImplOptions>:val=num:Int32:256)goldline",
    R"goldline(A1:type=<System.Runtime.CompilerServices.IntrinsicAttribute>:ctor=<System.Runtime.CompilerServices.IntrinsicAttribute..ctor>:err=False:F=0:N=0)goldline",
    R"goldline(E R:0600030F n=0)goldline",
    R"goldline(C method 06000029)goldline",
    R"goldline(E 06000029 n=1)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.DllImportAttribute>:ctor=<System.Runtime.InteropServices.DllImportAttribute..ctor>:err=False:F=1:N=1)goldline",
    R"goldline(A0:F0:type=<System.String>:val=str:"kernel32.dll")goldline",
    R"goldline(A0:N0:name=SetLastError:kind=Field:type=<System.Boolean>:val=bool:True)goldline",
    R"goldline(E R:06000029 n=1)goldline",
    R"goldline(A0:type=<System.Runtime.InteropServices.MarshalAsAttribute>:ctor=<System.Runtime.InteropServices.MarshalAsAttribute..ctor>:err=False:F=1:N=0)goldline",
    R"goldline(A0:F0:type=<System.Runtime.InteropServices.UnmanagedType>:val=num:Int32:2)goldline",
};

inline constexpr std::size_t kGoldMethodCuratedCount =
    sizeof(kGoldMethodCurated) / sizeof(kGoldMethodCurated[0]);

} // namespace ILSpy::Tests::MethodAttrGold
