// Copyright (c) 2026 ILSpy Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in the
// Software without restriction, including without limitation the rights to use, copy,
// modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
// and to permit persons to whom the Software is furnished to do so, subject to the
// following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
// FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
// OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

// Port of ICSharpCode.Decompiler/CSharp/Resolver/OverloadResolutionErrors.cs -- the
// `[Flags]` enum recording the per-candidate and overall errors of an overload-resolution
// attempt. This is the fourth `cpp/Decompiler/CSharp/Resolver/` leaf toward the
// `CSharpResolver` leaf deps (the long-pole remaining blocker of
// `TypeSystemAstBuilder` / `CSharpAmbience`), after the D467 twin Alias `ResolveResult`
// subclasses and the `NameLookupMode` enum. The C# source is a `[Flags]` enum with no
// underlying-type annotation (so `int`-backed, the C# default) and 13 flag members
// (`None = 0` plus 12 single-bit error flags `0x0001`..`0x1000`):
//   * `TooManyPositionalArguments` (0x0001) -- too many positional arguments.
//   * `NoParameterFoundForNamedArgument` (0x0002) -- a named argument mapped to no
//     parameter.
//   * `TypeInferenceFailed` (0x0004) -- type inference failed for a generic method.
//   * `WrongNumberOfTypeArguments` (0x0008) -- explicit type arguments did not match
//     the type-parameter count.
//   * `ConstructedTypeDoesNotSatisfyConstraint` (0x0010) -- a constructed type within
//     the formal parameters does not satisfy its constraint after substitution.
//   * `MissingArgumentForRequiredParameter` (0x0020) -- no argument was mapped to a
//     non-optional parameter.
//   * `MultipleArgumentsForSingleParameter` (0x0040) -- several arguments mapped to
//     a single (non-params-array) parameter.
//   * `ParameterPassingModeMismatch` (0x0080) -- `ref`/`out` passing mode does not
//     match for at least one parameter.
//   * `ArgumentTypeMismatch` (0x0100) -- an argument type cannot be converted to
//     the parameter type.
//   * `AmbiguousMatch` (0x0200) -- no unique best overload (an overall, not
//     per-candidate, error; does not prevent a candidate from being applicable).
//   * `Inaccessible` (0x0400) -- the member is not accessible (generated by member
//     lookup, not by overload resolution).
//   * `MethodConstraintsNotSatisfied` (0x0800) -- a generic method's constraints are
//     not satisfied (does not prevent a candidate from being applicable).
//   * `OutVarTypeMismatch` (0x1000) -- using `out var` instead of `out T` would
//     result in loss of type information.
//
// The C# `OverloadResolution` (the next `CSharp/Resolver` leaf toward the full
// 2986-line `CSharpResolver` class) accumulates these flags per candidate and OR-s
// them into the overall result; the `MethodGroupResolveResult` / `CSharpInvocation
// ResolveResult` surface carries the final mask. The enum is a self-contained `[Flags]`
// value type (no external dependencies), the same shape as the D376 `TypeSystemOptions`:
// a `std::int32_t`-backed `enum class` (the largest member `OutVarTypeMismatch =
// 0x1000` fits as a plain signed value; the C# `: int` / `[Flags]` underlying
// semantics). The `|`/`&`/`^`/`~` bitwise operators the C# `[Flags]` compiler generates
// implicitly are defined here as free functions (the C++ `enum class` does NOT have
// them), the `TypeSystemOptions` / `ConversionFlags` precedents.

#pragma once

#include <cstdint>

namespace ILSpy::Decompiler::CSharp::Resolver {

// The C# `[Flags] public enum OverloadResolutionErrors` (an `int`-backed enum). The
// `enum class` (scoped, no implicit conversion to/from `int`, matching the C# enum's
// typed usage) is backed by `std::int32_t` (the C# `int` default). The member order
// and values mirror the C# exactly (each individual flag's numeric value is the C#
// literal); `None = 0` is the no-error baseline. The 12 individual flags are
// disjoint single bits (`0x0001`..`0x1000`), so the `OverloadResolution`
// accumulator can OR them into a combined mask without clobbering.
enum class OverloadResolutionErrors : std::int32_t {
	None = 0,
	TooManyPositionalArguments = 0x0001,
	NoParameterFoundForNamedArgument = 0x0002,
	TypeInferenceFailed = 0x0004,
	WrongNumberOfTypeArguments = 0x0008,
	ConstructedTypeDoesNotSatisfyConstraint = 0x0010,
	MissingArgumentForRequiredParameter = 0x0020,
	MultipleArgumentsForSingleParameter = 0x0040,
	ParameterPassingModeMismatch = 0x0080,
	ArgumentTypeMismatch = 0x0100,
	AmbiguousMatch = 0x0200,
	Inaccessible = 0x0400,
	MethodConstraintsNotSatisfied = 0x0800,
	OutVarTypeMismatch = 0x1000,
};

// The `[Flags]` bitwise operators (the C# `[Flags]` enum has them implicitly; the C++
// `enum class` does NOT, so they are defined here). Part of the value type's core
// semantics -- accumulating per-candidate errors into an overall mask
// (`ArgumentTypeMismatch | TypeInferenceFailed`), testing a flag
// (`(errors & AmbiguousMatch) == AmbiguousMatch`, the pattern the `OverloadResolution`
// accumulator and the `MethodGroupResolveResult` / `CSharpInvocationResolveResult`
// surfaces use), NOT an output-stage helper, so they land now (the `TypeSystemOptions`
// / `ConversionFlags` precedent).
inline OverloadResolutionErrors operator|(OverloadResolutionErrors a, OverloadResolutionErrors b) {
	return static_cast<OverloadResolutionErrors>(
		static_cast<std::int32_t>(a) | static_cast<std::int32_t>(b));
}
inline OverloadResolutionErrors operator&(OverloadResolutionErrors a, OverloadResolutionErrors b) {
	return static_cast<OverloadResolutionErrors>(
		static_cast<std::int32_t>(a) & static_cast<std::int32_t>(b));
}
inline OverloadResolutionErrors operator^(OverloadResolutionErrors a, OverloadResolutionErrors b) {
	return static_cast<OverloadResolutionErrors>(
		static_cast<std::int32_t>(a) ^ static_cast<std::int32_t>(b));
}
inline OverloadResolutionErrors operator~(OverloadResolutionErrors a) {
	return static_cast<OverloadResolutionErrors>(~static_cast<std::int32_t>(a));
}

} // namespace ILSpy::Decompiler::CSharp::Resolver
